"use strict";
// Native explicit append under one retained Defect. All storage is disposable.
const {chromium,expect}=require('@playwright/test');
const {spawn,spawnSync}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{createHash}=require('node:crypto');
const {chooseTakeoff,chooseLibrary}=require('./section_navigation.cjs'),{clickProjectControl}=require('./project_actions.cjs'),{renderDrawing}=require('./viewer_helpers.cjs');
const {chooseNewPhysicalItem,startPhysicalItem}=require('./physical_dialogs.cjs');
const root=path.resolve(__dirname,'../..'),output=path.join(root,'.runtime/browser-qa',`library-barrier-import-${Date.now()}`);
fs.mkdirSync(output,{recursive:true});
const server=spawn(process.env.CEASEFIRE_PYTHON||'python',[path.join(__dirname,'project_library_fixture.py'),'--directory',output,'--takeoff-links'],{cwd:root,windowsHide:true});
let browser,page,info,logs='',current;const errors=[],evidence={};server.stderr.on('data',value=>logs+=value);
const ready=new Promise((resolve,reject)=>{let line='';const timer=setTimeout(()=>reject(new Error(`Fixture startup: ${logs}`)),120000);server.stdout.on('data',value=>{line+=value;if(line.includes('\n')){clearTimeout(timer);resolve(JSON.parse(line.split('\n')[0]));}});server.once('error',reject);server.once('exit',code=>{clearTimeout(timer);reject(new Error(`Fixture exited ${code}: ${logs}`));});});
const hash=file=>createHash('sha256').update(fs.readFileSync(file)).digest('hex'),details=()=>page.getByRole('complementary',{name:'Item Details',exact:true}),dialog=()=>page.getByRole('dialog');
const applicationFiles=['static/takeoff-library-links.js','static/takeoff-physical.js','static/takeoffs.js','static/takeoffs.css','estimator/firestopping_library.py','estimator/takeoff_library_links.py','estimator/takeoff_physical.py','estimator/takeoff_workspace.py'];
const applicationHashes=()=>Object.fromEntries(applicationFiles.map(file=>[file,hash(path.join(root,file))]));
const sourceBindings=applicationHashes();
async function idle(){await expect.poll(()=>page.evaluate(()=>window.CeasefireDesktop.status().busy)).toBe(false);}
async function snapshot(){await idle();const response=await page.request.get(await page.evaluate(()=>`${location.origin}/api/takeoffs/sessions/${window.CeasefireTakeoffs.sessionId()}`));assert.equal(response.status(),200,await response.text());current=(await response.json()).snapshot;return current;}
async function modal(title,values,submit){await expect(dialog().getByRole('heading',{name:title,exact:true})).toBeVisible();for(const [label,value]of Object.entries(values)){const field=dialog().getByLabel(label,{exact:true});if(await field.evaluate(el=>el.tagName)==='SELECT')await field.selectOption(String(value));else await field.fill(String(value));}await dialog().getByRole('button',{name:submit,exact:true}).click();}
async function selectLibrary(command=null){
  await expect(dialog().getByRole('heading',{name:'Search Firestopping Library',exact:true})).toBeVisible();
  const select=dialog().getByLabel('Library item',{exact:true});await expect(select).toBeEnabled();
  await expect(select.locator(`option[value="${info.item_id}"]`)).toHaveText('FL-ID-001; Core Hole; Concrete; Vertical; Copper service; -/90/90');evidence.sixLiteralPickerFields=true;
  const response=command?page.waitForResponse(reply=>reply.url().endsWith('/commands')&&reply.request().postDataJSON()?.op===command):null;
  await select.selectOption(info.item_id);await expect(dialog().getByRole('heading',{name:'Complete selected item details',exact:true})).toBeVisible();
  const quantity=dialog().getByLabel('Item QTY',{exact:true});await expect(quantity).toHaveAttribute('min','1');await expect(quantity).toHaveAttribute('step','1');await expect(dialog()).toContainText('physical service count');
  if(await dialog().getByLabel('Location',{exact:true}).count())await dialog().getByLabel('Location',{exact:true}).fill('L02 fixture north');
  await modal('Complete selected item details',{'Item QTY':'700'},'Use item details');
  if(response){const reply=await response;assert.equal(reply.status(),200,await reply.text());await idle();}
}
function assertCount(index){const service=current.physical.services[index],assignment=current.library_assignments.records[index];assert.equal(service.quantity,700);assert.ok(!Object.hasOwn(service,'library_quantity'));assert.equal(assignment.draft_quantity,700);assert.deepEqual(assignment.quantity_source,{version:1,kind:'services'});assert.equal(assignment.schedule_binding,null);}
async function appendStart(choice){await details().getByRole('button',{name:'Add Library Item',exact:true}).click();await modal('Choose barrier for library item',{'Barrier choice':choice},'Continue');}
async function inspect(kind,id){await details().getByLabel(`${kind} ID in Item Details`,{exact:true}).selectOption(id);await idle();}
async function paneOrder(count,hasParent){
  await expect(details().locator('.takeoff-library-summary')).toHaveCount(count);
  const order=await details().evaluate((pane,hasParent)=>{
    const children=[...pane.children],index=selector=>children.findIndex(child=>child.matches(selector));
    const choose=children.findIndex(child=>child.tagName==='BUTTON'&&child.textContent==='Add Library Item'),service=children.findIndex(child=>child.tagName==='BUTTON'&&child.textContent==='Add Service'),barrier=children.findIndex(child=>child.tagName==='BUTTON'&&child.textContent==='Add Barrier'),navigation=index('.takeoff-physical-navigation'),parent=children.findIndex(child=>child.tagName==='BUTTON'&&child.textContent==='Change Parent'),actions=index('.takeoff-physical-inspector-actions'),fields=children.flatMap((child,i)=>child.matches('.field')?[i]:[]),cards=children.flatMap((child,i)=>child.matches('.takeoff-library-summary')?[i]:[]);
    return {choose,service,barrier,navigation,parent,actions,fields,cards,buttons:children.flatMap((child,i)=>child.tagName==='BUTTON'?[i]:[]),total:children.length,hasParent};
  },hasParent);
  assert.ok(order.choose>=0);assert.equal(order.service,order.choose+1);assert.equal(order.actions,order.choose+2);assert.equal(order.navigation,order.actions+(order.barrier>=0?2:1));if(order.barrier>=0)assert.equal(order.barrier,order.actions+1);assert.equal(order.parent,hasParent?order.navigation+1:-1);
  assert.deepEqual(order.cards,Array.from({length:count},(_,i)=>order.total-count+i));assert.ok(order.fields.every(index=>index>order.actions&&index<order.cards[0]));
  assert.ok(order.buttons.every(index=>index<order.fields[0]));
  await expect(details().getByRole('button',{name:'Delete draft record',exact:true})).toHaveCount(1);await expect(details().getByRole('button',{name:'Discard unfinished physical edits',exact:true})).toHaveCount(1);
  (evidence.itemDetailsOrder||=[]).push(order);
}
async function facets(locator){return locator.locator('select[data-library-filter]').evaluateAll(elements=>elements.map(el=>({key:el.dataset.libraryFilter,label:el.closest('label').querySelector('span').textContent,options:[...el.options].map(option=>({value:option.value,label:option.textContent}))})));}
(async()=>{
  info=await ready;assert.notEqual(info.port,8765);const source=path.join(output,'reference-library/library.json'),sourceHash=hash(source),pdfHash=hash(info.fixture);
  browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1360,height:1000}});page.setDefaultTimeout(30000);page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`http://127.0.0.1:${info.port}/`);await page.waitForFunction(()=>window.CeasefireDesktop?.status().ready&&!window.CeasefireDesktop.status().busy);
  await chooseLibrary(page,'penetration');
  // The Library browser is a section, not a landmark on older installations.
  const nativeFilters=page.locator('.library-browser').filter({has:page.locator('[data-library-results="penetration"]')});await expect(nativeFilters.locator('select[data-library-filter="substrate"]')).toBeVisible();const expectedFacets=(await facets(nativeFilters)).filter(value=>value.key!=='technical_reference');
  await page.getByRole('button',{name:'Takeoffs',exact:true}).click();await renderDrawing(page,()=>page.locator('#takeoff-upload').setInputFiles(info.fixture),1);await chooseTakeoff(page,'Defect Reports');await idle();
  const originalPen=await page.evaluate(async()=>{await window.CeasefirePenetrations.completeProjectSnapshot();return window.CeasefirePenetrations.projectSnapshot();}),calculators=await page.evaluate(()=>window.CeasefireCalculators.completeProjectSnapshot());
  await page.getByRole('button',{name:'Call-out',exact:true}).click();const box=await page.locator('.takeoff-overlay').boundingBox();await page.mouse.click(box.x+box.width*.55,box.y+box.height*.4);await modal('Add Defect',{'Choose item':'search'},'Continue');
  await expect(dialog().locator('select[data-library-filter="substrate"]')).toBeVisible();assert.deepEqual(await facets(dialog()),expectedFacets);evidence.sameActualLibraryFacets=true;
  await expect(dialog().getByLabel('Technical Reference',{exact:true})).toHaveCount(0);evidence.pickerTechnicalReferenceRemoved=true;
  await selectLibrary('draft_library_assignment');await snapshot();const defect=structuredClone(current.physical.defects[0]),initialBarrier=structuredClone(current.physical.barriers[0]);assertCount(0);assert.equal(defect.fields.location,'L02 fixture north');assert.equal(current.library_assignments.records[0].draft_location,'L02 fixture north');assert.deepEqual(await page.evaluate(()=>window.CeasefirePenetrations.projectSnapshot()),originalPen);evidence.explicitPhysicalCountWithoutScheduleChange=true;
  await paneOrder(1,false);await inspect('Service',current.physical.services[0].id);await paneOrder(1,true);await inspect('Defect',defect.id);
  // First New Barrier choice; selection adds immediately with no import review.
  await appendStart('new');await selectLibrary('import_library_item');await expect(details().getByRole('button',{name:'Add Library Item',exact:true})).toBeVisible();await snapshot();
  assert.equal(current.physical.defects.length,1);assert.deepEqual(current.physical.defects[0],defect);assert.equal(current.physical.barriers.length,2);assert.equal(current.physical.services.length,2);
  const addedBarrier=structuredClone(current.physical.barriers[1]),newAssignment=structuredClone(current.library_assignments.records[1]);assert.equal(addedBarrier.defect_id,defect.id);assert.equal(addedBarrier.fields.barrier_type,'Core Hole');assert.equal(addedBarrier.fields.substrate,'Concrete');assert.equal(addedBarrier.fields.orientation,'Vertical');assert.deepEqual(addedBarrier.marker,defect.annotation);assert.equal(newAssignment.barrier_selection.choice,'new');assertCount(1);assert.deepEqual(await page.evaluate(()=>window.CeasefirePenetrations.projectSnapshot()),originalPen);evidence.newBarrierSameDefectExactSource=true;
  await paneOrder(1,true);await inspect('Defect',defect.id);await paneOrder(2,false);
  const parentLabel=page.locator(`.takeoff-physical-callout[data-physical-id="${defect.id}"]`);await expect(parentLabel).toHaveCount(1);await expect(parentLabel).toContainText(current.physical.services[1].display_id);await expect(page.locator(`.takeoff-physical-callout[data-physical-id="${addedBarrier.id}"]`)).toHaveCount(0);evidence.inheritedBarrierUsesParentLabel=true;
  // Existing matching Barrier choice explicitly names ID/type/substrate/orientation.
  await appendStart('existing');await expect(dialog().getByRole('heading',{name:'Choose Existing Barrier',exact:true})).toBeVisible();const choice=dialog().getByLabel('Existing Barrier',{exact:true});await expect(choice).toHaveValue('');await expect(choice.locator(`option[value="${addedBarrier.id}"]`)).toHaveText(`${addedBarrier.display_id} · Core Hole · Concrete · Vertical`);
  await modal('Choose Existing Barrier',{'Existing Barrier':addedBarrier.id},'Use Existing Barrier');await selectLibrary('import_library_item');await snapshot();assert.equal(current.physical.barriers.length,2);assert.deepEqual(current.physical.barriers[1],addedBarrier);assert.equal(current.physical.services.length,3);assertCount(2);assert.equal(current.library_assignments.records[2].barrier_selection.choice,'existing');assert.deepEqual(current.library_assignments.records[2].barrier_selection.differences,[]);evidence.existingBarrierAddsOnlyService=true;
  // Native edit creates a real mismatch; cancellation returns to Search unchanged.
  await inspect('Barrier',addedBarrier.id);const orientationReply=page.waitForResponse(reply=>reply.url().endsWith('/physical/apply'));await details().getByLabel('Substrate orientation',{exact:true}).selectOption('Horizontal');await details().getByLabel('Substrate orientation',{exact:true}).press('Tab');assert.equal((await orientationReply).status(),200);await idle();await snapshot();const retained=structuredClone(current.physical.barriers[1]);assert.equal(retained.fields.orientation,'Horizontal');const beforeCancel=structuredClone(current);
  await appendStart('existing');await modal('Choose Existing Barrier',{'Existing Barrier':addedBarrier.id},'Use Existing Barrier');await selectLibrary();await expect(dialog().getByRole('heading',{name:'Library barrier mismatch',exact:true})).toBeVisible();await expect(dialog()).toContainText('Existing Barrier = Horizontal; selected library = Vertical');await dialog().getByRole('button',{name:'Cancel',exact:true}).click();await expect(dialog().getByRole('heading',{name:'Search Firestopping Library',exact:true})).toBeVisible();
  // Read the server directly while the dialog is open (no UI mutation or save).
  const cancelled=await page.request.get(await page.evaluate(()=>`${location.origin}/api/takeoffs/sessions/${window.CeasefireTakeoffs.sessionId()}`));assert.deepEqual((await cancelled.json()).snapshot,beforeCancel);evidence.cancelReturnsToSearchNoMutation=true;
  await selectLibrary();const mismatchReply=page.waitForResponse(reply=>reply.url().endsWith('/commands')&&reply.request().postDataJSON()?.op==='import_library_item');await modal('Library barrier mismatch',{},'Continue');assert.equal((await mismatchReply).status(),200);await snapshot();assert.equal(current.physical.defects.length,1);assert.deepEqual(current.physical.defects[0],defect);assert.equal(current.physical.barriers.length,2);assert.deepEqual(current.physical.barriers[1],retained);assert.equal(current.physical.services.length,4);const mismatch=current.library_assignments.records[3];assert.equal(mismatch.barrier_selection.mismatch_accepted,true);assert.deepEqual(mismatch.barrier_selection.differences,[{field:'orientation',selected:'Vertical',retained:'Horizontal'}]);assert.equal(current.physical.services[3].uncertainty.state,'human_review_required');assertCount(3);assert.deepEqual(await page.evaluate(()=>window.CeasefirePenetrations.projectSnapshot()),originalPen);evidence.continueRetainsUnapprovedMismatch=true;
  await expect(parentLabel).toContainText(current.physical.services[3].display_id);await expect(parentLabel).toContainText('Horizontal');await expect(page.locator(`.takeoff-physical-callout[data-physical-id="${addedBarrier.id}"]`)).toHaveCount(0);
  await page.screenshot({path:path.join(output,'appended-library-barriers.png')});
  // One atomic Undo preserves identities and provenance, without orphan schedule rows.
  await chooseTakeoff(page,'Steel');const undoReply=page.waitForResponse(reply=>reply.url().endsWith('/commands')&&reply.request().postDataJSON()?.op==='undo');undoReply.catch(()=>{});await page.getByRole('button',{name:'Undo last edit',exact:true}).click();assert.equal((await undoReply).status(),200);await chooseTakeoff(page,'Defect Reports');await snapshot();assert.equal(current.physical.services[3].deleted,true);assert.deepEqual(current.physical.barriers[1],retained);assert.equal(current.library_assignments.records[3].state,'needs_recheck');assert.deepEqual(current.items,[]);assert.deepEqual(await page.evaluate(()=>window.CeasefirePenetrations.projectSnapshot()),originalPen);evidence.undoRetainsIdentity=true;
  if(await page.getByRole('button',{name:'Close Item Details',exact:true}).isVisible())await page.getByRole('button',{name:'Close Item Details',exact:true}).click();const saved=structuredClone(current);const response=page.waitForResponse(reply=>new URL(reply.url()).pathname==='/api/project/save-as');response.catch(()=>{});await clickProjectControl(page,'Save');assert.equal((await response).status(),200);await expect(page.locator('#project-save-state')).toHaveText('Saved project');const project=JSON.parse(fs.readFileSync(info.project,'utf8'));assert.deepEqual(project.takeoffs.library_assignments,saved.library_assignments);
  const oldSession=await page.evaluate(()=>window.CeasefireTakeoffs.sessionId()),reopenedScan=page.waitForResponse(reply=>reply.url().endsWith('/auto-calibrate')&&!reply.url().includes(`/sessions/${oldSession}/`));reopenedScan.catch(()=>{});
  await clickProjectControl(page,'Load');await modal('Load this project?',{},'Load Project');await expect(page.locator('#project-save-state')).toHaveText('Saved project');await page.getByRole('button',{name:'Takeoffs',exact:true}).click();await chooseTakeoff(page,'Defect Reports');const scanned=await reopenedScan;assert.equal(scanned.status(),200,await scanned.text());await snapshot();assert.deepEqual(current.physical,saved.physical);assert.deepEqual(current.library_assignments,saved.library_assignments);evidence.projectRoundtrip=true;
  const pdf=path.join(output,'appended-library-barriers.pdf'),download=page.waitForEvent('download');await page.evaluate(()=>window.CeasefireTakeoffs.downloadDrawing());await(await download).saveAs(pdf);assert.ok(fs.statSync(pdf).size>1000);evidence.markedPdf=true;
  const extracted=spawnSync(process.env.CEASEFIRE_PYTHON||'python',['-c','from pypdf import PdfReader; import sys; print("".join(page.extract_text() or "" for page in PdfReader(sys.argv[1]).pages))',pdf],{cwd:root,windowsHide:true,encoding:'utf8',maxBuffer:10*1024*1024});assert.equal(extracted.status,0,extracted.stderr);const text=extracted.stdout.replace(/\s/g,'');for(const service of current.physical.services.filter(value=>!value.deleted))assert.equal(text.split(service.display_id).length-1,1,`${service.display_id} appears exactly once in the parent PDF label`);evidence.pdfCombinedLabelContainsEveryServiceOnce=true;
  assert.deepEqual(current.physical.defects[0].annotation,defect.annotation);assert.deepEqual(current.physical.barriers[0],initialBarrier);assert.equal(hash(source),sourceHash);assert.equal(hash(info.fixture),pdfHash);assert.deepEqual(await page.evaluate(()=>window.CeasefireCalculators.projectSnapshot()),calculators);assert.deepEqual(await page.evaluate(()=>window.CeasefirePenetrations.projectSnapshot()),originalPen);assert.deepEqual(errors,[]);
  await page.locator(`tr[data-physical-id="${current.physical.services[0].id}"]`).getByRole('button',{name:'Edit',exact:true}).click();await idle();const sharedVisibility=details().getByRole('button',{name:'Visibility',exact:true}),beforeHiddenParent=structuredClone(current);await expect(sharedVisibility).toHaveAttribute('title','Hide callout D-0001');await sharedVisibility.click();await expect(parentLabel).toHaveCount(0);await expect(page.locator(`.takeoff-physical-callout[data-physical-id="${addedBarrier.id}"]`)).toHaveCount(0);const hiddenDownload=page.waitForEvent('download');await page.evaluate(()=>window.CeasefireTakeoffs.downloadDrawing());const hiddenPdf=path.join(output,'hidden-shared-callout.pdf');await(await hiddenDownload).saveAs(hiddenPdf);const hiddenText=spawnSync(process.env.CEASEFIRE_PYTHON||'python',['-c','from pypdf import PdfReader; import sys; print("".join(page.extract_text() or "" for page in PdfReader(sys.argv[1]).pages))',hiddenPdf],{cwd:root,windowsHide:true,encoding:'utf8'});assert.equal(hiddenText.status,0,hiddenText.stderr);assert.ok(!hiddenText.stdout.includes('D-0001'));for(const service of current.physical.services.filter(value=>!value.deleted))assert.ok(!hiddenText.stdout.includes(service.display_id));assert.deepEqual(await snapshot(),beforeHiddenParent);await sharedVisibility.click();await expect(parentLabel).toHaveCount(1);assert.deepEqual(await snapshot(),beforeHiddenParent);evidence.hiddenSharedCalloutExcludedFromPdf=true;
  // Service Plans uses the same real Search Item chooser, rooted at Barrier.
  const retainedReport=structuredClone(current.physical);await chooseTakeoff(page,'Service Plans');await renderDrawing(page,()=>page.getByRole('button',{name:'Fit page',exact:true}).click());await startPhysicalItem(page);await modal('Add Barrier',{'Choose item':'search'},'Continue');await selectLibrary('draft_library_assignment');await snapshot();
  assert.equal(current.service_plans.version,3);assert.ok(!Object.hasOwn(current.service_plans,'defects'));assert.equal(current.service_plans.barriers.length,1);assert.equal(current.service_plans.services.length,1);
  const planBarrier=structuredClone(current.service_plans.barriers[0]),planService=structuredClone(current.service_plans.services[0]);assert.ok(!Object.hasOwn(planBarrier,'defect_id'));assert.equal(planBarrier.fields.frl,'-/90/90');assert.equal(planBarrier.fields.location,'L02 fixture north');assert.equal(planService.quantity,700);assert.equal(planService.barrier_id,planBarrier.id);assert.deepEqual(current.physical,retainedReport);assert.deepEqual(current.library_assignments.records.at(-1).members.map(member=>member.id).sort(),[planBarrier.id,planService.id].sort());assert.equal(current.library_assignments.records.at(-1).schedule_binding,null);await expect(page.locator(`.takeoff-physical-callout[data-physical-id="${planBarrier.id}"]`)).toBeVisible();
  // Append from a selected Service to its explicit Existing Barrier.
  await inspect('Service',planService.id);await appendStart('existing');await modal('Choose Existing Barrier',{'Existing Barrier':planBarrier.id},'Use Existing Barrier');await selectLibrary('import_library_item');await snapshot();assert.equal(current.service_plans.barriers.length,1);assert.equal(current.service_plans.services.length,2);assert.deepEqual(current.service_plans.barriers[0],planBarrier);assert.deepEqual(current.service_plans.services[0],planService);assert.equal(current.service_plans.services[1].barrier_id,planBarrier.id);assert.equal(current.service_plans.services[1].quantity,700);assert.equal(current.library_assignments.records.at(-1).barrier_selection.choice,'existing');
  // A real observed mismatch is reviewed, cancelled unchanged, then retained.
  await inspect('Barrier',planBarrier.id);const planOrientation=page.waitForResponse(reply=>reply.url().endsWith('/physical/apply'));await details().getByLabel('Substrate orientation',{exact:true}).selectOption('Horizontal');await details().getByLabel('Substrate orientation',{exact:true}).press('Tab');assert.equal((await planOrientation).status(),200);await snapshot();const retainedPlan=structuredClone(current.service_plans.barriers[0]),cancelPlan=structuredClone(current);
  await appendStart('existing');await modal('Choose Existing Barrier',{'Existing Barrier':planBarrier.id},'Use Existing Barrier');await selectLibrary();await expect(dialog().getByRole('heading',{name:'Library barrier mismatch',exact:true})).toBeVisible();await expect(dialog()).toContainText('Existing Barrier = Horizontal; selected library = Vertical');await dialog().getByRole('button',{name:'Cancel',exact:true}).click();await expect(dialog().getByRole('heading',{name:'Search Firestopping Library',exact:true})).toBeVisible();const cancelledPlan=await page.request.get(await page.evaluate(()=>`${location.origin}/api/takeoffs/sessions/${window.CeasefireTakeoffs.sessionId()}`));assert.deepEqual((await cancelledPlan.json()).snapshot,cancelPlan);
  await selectLibrary();const planMismatch=page.waitForResponse(reply=>reply.url().endsWith('/commands')&&reply.request().postDataJSON()?.op==='import_library_item');await modal('Library barrier mismatch',{},'Continue');assert.equal((await planMismatch).status(),200);await snapshot();assert.deepEqual(current.service_plans.barriers[0],retainedPlan);assert.deepEqual(current.service_plans.services[0],planService);assert.equal(current.service_plans.services.length,3);assert.equal(current.service_plans.services[2].barrier_id,planBarrier.id);assert.equal(current.service_plans.services[2].quantity,700);assert.equal(current.library_assignments.records.at(-1).barrier_selection.mismatch_accepted,true);
  // New Barrier adopts literal library fields without inventing source linkage.
  await appendStart('new');await selectLibrary('import_library_item');await snapshot();assert.equal(current.service_plans.barriers.length,2);const importedPlan=structuredClone(current.service_plans.barriers[1]);assert.equal(importedPlan.fields.substrate,'Concrete');assert.equal(importedPlan.fields.orientation,'Vertical');assert.equal(importedPlan.fields.frl,'-/90/90');assert.equal(importedPlan.fields.location,'L02 fixture north');assert.ok(!importedPlan.marker);assert.ok(!Object.hasOwn(importedPlan,'defect_id'));assert.equal(current.service_plans.services.at(-1).barrier_id,importedPlan.id);assert.equal(current.service_plans.services.at(-1).quantity,700);assert.deepEqual(current.service_plans.barriers[0],retainedPlan);assert.deepEqual(current.service_plans.services[0],planService);assert.deepEqual(current.physical,retainedReport);assert.deepEqual(await page.evaluate(()=>window.CeasefirePenetrations.projectSnapshot()),originalPen);evidence.servicePlansAppendParity={existingRetained:true,oldServiceCountRetained:true,mismatchCancelUnchanged:true,mismatchExplicitContinue:true,newLiteralSubstrate:true,newRootUnplaced:true};
  await inspect('Barrier',planBarrier.id);await startPhysicalItem(page,[.35,.6]);await chooseNewPhysicalItem(page,'barrier');const secondApply=page.waitForResponse(reply=>reply.url().endsWith('/physical/apply'));await modal('Create draft barrier',{'Location':'Independent manual barrier'},'Preview new draft');await modal('Create one draft barrier?',{},'Apply draft change');assert.equal((await secondApply).status(),200);await snapshot();const secondPlan=current.service_plans.barriers.at(-1);
  await inspect('Service',planService.id);const visibility=details().getByRole('button',{name:'Visibility',exact:true}),firstCallout=page.locator(`.takeoff-physical-callout[data-physical-id="${planBarrier.id}"]`),secondCallout=page.locator(`.takeoff-physical-callout[data-physical-id="${secondPlan.id}"]`),beforeVisibility=structuredClone(current);await expect(visibility).toHaveAttribute('title','Hide callout B-0001');await visibility.click();await expect(visibility).toHaveAttribute('aria-pressed','true');await expect(firstCallout).toHaveCount(0);await expect(secondCallout).toBeVisible();await expect(details()).toBeVisible();assert.deepEqual(await snapshot(),beforeVisibility);await visibility.click();await expect(firstCallout).toBeVisible();await expect(secondCallout).toBeVisible();assert.deepEqual(await snapshot(),beforeVisibility);
  // Hold the ordinary note autosave so Visibility must work without flushing
  // or replacing its pending physical editor. Release it after view checks.
  const pendingNote='Pending note retained through Visibility',notes=details().getByLabel('Notes',{exact:true}),noteHandle=await notes.elementHandle(),noteRequests=[];let releaseNote;const heldNote=new Promise(resolve=>releaseNote=resolve);await page.route('**/physical/preview',async route=>{const body=route.request().postDataJSON();if(body.commands?.some(command=>command.entity_id===planService.id&&command.changes?.fields?.notes===pendingNote)){noteRequests.push(body);await heldNote;}await route.continue();});
  try{await notes.fill(pendingNote);await visibility.click();await expect(visibility).toHaveAttribute('aria-pressed','true');await expect(firstCallout).toHaveCount(0);await expect(secondCallout).toBeVisible();await expect(notes).toHaveValue(pendingNote);assert.equal(await noteHandle.evaluate(el=>el.isConnected),true);const pendingState=await page.request.get(await page.evaluate(()=>`${location.origin}/api/takeoffs/sessions/${window.CeasefireTakeoffs.sessionId()}`));assert.deepEqual((await pendingState.json()).snapshot,beforeVisibility);await expect.poll(()=>noteRequests.length).toBe(1);}finally{releaseNote();}
  await expect.poll(async()=>{await snapshot();return current.service_plans.services.find(service=>service.id===planService.id).fields.notes;}).toBe(pendingNote);await page.unroute('**/physical/preview');assert.equal(noteRequests.length,1);assert.equal(current.service_plans.services.find(service=>service.id===planService.id).quantity,700);await visibility.click();await expect(firstCallout).toBeVisible();await expect(secondCallout).toBeVisible();evidence.pendingNoteSurvivesVisibility=true;
  for(const width of [1146,390]){await page.setViewportSize({width,height:900});await details().scrollIntoViewIfNeeded();const bounds=await visibility.evaluate(el=>{const box=el.getBoundingClientRect(),icon=el.querySelector('img').getBoundingClientRect();return {width:box.width,height:box.height,iconWidth:icon.width,iconHeight:icon.height};});assert.deepEqual(bounds,{width:38,height:38,iconWidth:32,iconHeight:32});const serviceBounds=await details().getByRole('button',{name:'Add service in Item Details',exact:true}).evaluate(el=>({text:el.textContent,width:el.getBoundingClientRect().width,pane:el.parentElement.getBoundingClientRect().width}));assert.equal(serviceBounds.text,'Add Service');assert.ok(serviceBounds.width>=serviceBounds.pane-40);await page.screenshot({path:path.join(output,`service-plan-library-visibility-${width}.png`)});}
  assert.deepEqual(current.physical,retainedReport);assert.deepEqual(await page.evaluate(()=>window.CeasefirePenetrations.projectSnapshot()),originalPen);assert.deepEqual(await page.evaluate(()=>window.CeasefireCalculators.projectSnapshot()),calculators);assert.equal(hash(source),sourceHash);assert.equal(hash(info.fixture),pdfHash);evidence.servicePlansLibrary={barrierId:planBarrier.id,serviceId:planService.id,quantity:700,rootVersion3:true,noDefect:true,sourceCallout:true,childVisibilityTargetsOnlyOwner:true,visibilityViewOnly:true,iconGeometry:[1146,390]};assert.deepEqual(errors,[]);
  assert.deepEqual(applicationHashes(),sourceBindings,'Application source must remain frozen throughout this acceptance');
  fs.writeFileSync(path.join(output,'result.json'),JSON.stringify({status:'PASS',port:info.port,errors,evidence,defectId:defect.id,barrierId:addedBarrier.id,sourceSha256:sourceHash,pdfSha256:pdfHash,applicationSourceSha256:sourceBindings,fixtureSha256:hash(__filename)},null,2));console.log(`PASS library barrier import native acceptance: ${output}`);
})().catch(async error=>{console.error(error.stack);console.error(logs);if(page){await page.screenshot({path:path.join(output,'failure.png')}).catch(()=>{});const diagnostic=await page.evaluate(()=>({desktop:window.CeasefireDesktop.status(),busyNodes:[...document.querySelectorAll('dialog[open], [aria-busy="true"]')].map(el=>({tag:el.tagName,id:el.id,class:el.className,hidden:!!el.closest('[hidden]'),text:el.textContent.slice(0,300)})),takeoffs:window.CeasefireTakeoffs.hasPendingOperation()})).catch(()=>null);fs.writeFileSync(path.join(output,'failure-state.json'),JSON.stringify(diagnostic,null,2));}process.exitCode=1;}).finally(async()=>{await browser?.close();server.kill();});
