"use strict";
// Native explicit append under one retained Defect. All storage is disposable.
const {chromium,expect}=require('@playwright/test');
const {spawn,spawnSync}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{createHash}=require('node:crypto');
const {chooseTakeoff,chooseLibrary}=require('./section_navigation.cjs'),{clickProjectControl}=require('./project_actions.cjs'),{renderDrawing}=require('./viewer_helpers.cjs');
const root=path.resolve(__dirname,'../..'),output=path.join(root,'.runtime/browser-qa',`library-barrier-import-${Date.now()}`);
fs.mkdirSync(output,{recursive:true});
const server=spawn(process.env.CEASEFIRE_PYTHON||'python',[path.join(__dirname,'project_library_fixture.py'),'--directory',output,'--takeoff-links'],{cwd:root,windowsHide:true});
let browser,page,info,logs='',current;const errors=[],evidence={};server.stderr.on('data',value=>logs+=value);
const ready=new Promise((resolve,reject)=>{let line='';const timer=setTimeout(()=>reject(new Error(`Fixture startup: ${logs}`)),120000);server.stdout.on('data',value=>{line+=value;if(line.includes('\n')){clearTimeout(timer);resolve(JSON.parse(line.split('\n')[0]));}});server.once('error',reject);server.once('exit',code=>{clearTimeout(timer);reject(new Error(`Fixture exited ${code}: ${logs}`));});});
const hash=file=>createHash('sha256').update(fs.readFileSync(file)).digest('hex'),details=()=>page.getByRole('complementary',{name:'Item Details',exact:true}),dialog=()=>page.getByRole('dialog');
async function idle(){await expect.poll(()=>page.evaluate(()=>window.CeasefireDesktop.status().busy)).toBe(false);}
async function snapshot(){await idle();const response=await page.request.get(await page.evaluate(()=>`${location.origin}/api/takeoffs/sessions/${window.CeasefireTakeoffs.sessionId()}`));assert.equal(response.status(),200,await response.text());current=(await response.json()).snapshot;return current;}
async function modal(title,values,submit){await expect(dialog().getByRole('heading',{name:title,exact:true})).toBeVisible();for(const [label,value]of Object.entries(values)){const field=dialog().getByLabel(label,{exact:true});if(await field.evaluate(el=>el.tagName)==='SELECT')await field.selectOption(String(value));else await field.fill(String(value));}await dialog().getByRole('button',{name:submit,exact:true}).click();}
async function selectLibrary(command=null){await expect(dialog().getByRole('heading',{name:'Search Firestopping Library',exact:true})).toBeVisible();await expect(dialog().getByLabel('Library item',{exact:true})).toBeEnabled();const response=command?page.waitForResponse(reply=>reply.url().endsWith('/commands')&&reply.request().postDataJSON()?.op===command):null;await dialog().getByLabel('Library item',{exact:true}).selectOption(info.item_id);await expect(dialog().getByRole('heading',{name:'Complete selected item details',exact:true})).toBeVisible();if(await dialog().getByLabel('Location',{exact:true}).count())await dialog().getByLabel('Location',{exact:true}).fill('L02 fixture north');await modal('Complete selected item details',{'Item QTY':'2.345678901'},'Use item details');if(response){const reply=await response;assert.equal(reply.status(),200,await reply.text());await idle();}}
async function appendStart(choice){await details().getByRole('button',{name:'Choose library item for selected records',exact:true}).click();await modal('Choose barrier for library item',{'Barrier choice':choice},'Continue');}
async function inspect(kind,id){await details().getByLabel(`${kind} ID in Item Details`,{exact:true}).selectOption(id);await idle();}
async function facets(locator){return locator.locator('select[data-library-filter]').evaluateAll(elements=>elements.map(el=>({key:el.dataset.libraryFilter,label:el.closest('label').querySelector('span').textContent,options:[...el.options].map(option=>({value:option.value,label:option.textContent}))})));}
(async()=>{
  info=await ready;assert.notEqual(info.port,8765);const source=path.join(output,'reference-library/library.json'),sourceHash=hash(source),pdfHash=hash(info.fixture);
  browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1360,height:1000}});page.setDefaultTimeout(30000);page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`http://127.0.0.1:${info.port}/`);await page.waitForFunction(()=>window.CeasefireDesktop?.status().ready&&!window.CeasefireDesktop.status().busy);
  await chooseLibrary(page,'penetration');
  // The Library browser is a section, not a landmark on older installations.
  const nativeFilters=page.locator('.library-browser').filter({has:page.locator('[data-library-results="penetration"]')});await expect(nativeFilters.locator('select[data-library-filter="substrate"]')).toBeVisible();const expectedFacets=(await facets(nativeFilters)).filter(value=>value.key!=='technical_reference');
  await page.getByRole('button',{name:'Takeoffs',exact:true}).click();await renderDrawing(page,()=>page.locator('#takeoff-upload').setInputFiles(info.fixture),1);await chooseTakeoff(page,'Defect Reports');await idle();
  const originalPen=await page.evaluate(async()=>{await window.CeasefirePenetrations.completeProjectSnapshot();return window.CeasefirePenetrations.projectSnapshot();}),calculators=await page.evaluate(()=>window.CeasefireCalculators.completeProjectSnapshot());
  await page.getByRole('button',{name:'Call-out',exact:true}).click();const box=await page.locator('.takeoff-overlay').boundingBox();await page.mouse.click(box.x+box.width*.55,box.y+box.height*.4);await modal('Add Defect',{'Choose item':'search'},'Continue');
  await expect(dialog().locator('select[data-library-filter="substrate"]')).toBeVisible();assert.deepEqual(await facets(dialog()),expectedFacets);evidence.sameActualLibraryFacets=true;
  await expect(dialog().getByLabel('Technical Reference',{exact:true})).toHaveCount(0);evidence.pickerTechnicalReferenceRemoved=true;
  await selectLibrary('draft_library_assignment');await snapshot();const defect=structuredClone(current.physical.defects[0]),initialBarrier=structuredClone(current.physical.barriers[0]);assert.equal(current.physical.services[0].quantity,null);assert.equal(defect.fields.location,'L02 fixture north');assert.equal(current.library_assignments.records[0].draft_quantity,2.345678901);assert.equal(current.library_assignments.records[0].draft_location,'L02 fixture north');assert.equal(current.library_assignments.records[0].schedule_binding,null);assert.deepEqual(await page.evaluate(()=>window.CeasefirePenetrations.projectSnapshot()),originalPen);evidence.explicitDraftDetailsWithoutScheduleChange=true;
  // First New Barrier choice; selection adds immediately with no import review.
  await appendStart('new');await selectLibrary('import_library_item');await expect(details().getByRole('button',{name:'Choose library item for selected records',exact:true})).toBeVisible();await snapshot();
  assert.equal(current.physical.defects.length,1);assert.deepEqual(current.physical.defects[0],defect);assert.equal(current.physical.barriers.length,2);assert.equal(current.physical.services.length,2);
  const addedBarrier=structuredClone(current.physical.barriers[1]),newAssignment=structuredClone(current.library_assignments.records[1]);assert.equal(addedBarrier.defect_id,defect.id);assert.equal(addedBarrier.fields.barrier_type,'Core Hole');assert.equal(addedBarrier.fields.substrate,'Concrete');assert.equal(addedBarrier.fields.orientation,'Vertical');assert.deepEqual(addedBarrier.marker,defect.annotation);assert.equal(newAssignment.barrier_selection.choice,'new');assert.equal(current.physical.services[1].quantity,null);assert.deepEqual(await page.evaluate(()=>window.CeasefirePenetrations.projectSnapshot()),originalPen);evidence.newBarrierSameDefectExactSource=true;
  const parentLabel=page.locator(`.takeoff-physical-callout[data-physical-id="${defect.id}"]`);await expect(parentLabel).toHaveCount(1);await expect(parentLabel).toContainText(current.physical.services[1].display_id);await expect(page.locator(`.takeoff-physical-callout[data-physical-id="${addedBarrier.id}"]`)).toHaveCount(0);evidence.inheritedBarrierUsesParentLabel=true;
  // Existing matching Barrier choice explicitly names ID/type/substrate/orientation.
  await appendStart('existing');await expect(dialog().getByRole('heading',{name:'Choose Existing Barrier',exact:true})).toBeVisible();const choice=dialog().getByLabel('Existing Barrier',{exact:true});await expect(choice).toHaveValue('');await expect(choice.locator(`option[value="${addedBarrier.id}"]`)).toHaveText(`${addedBarrier.display_id} · Core Hole · Concrete · Vertical`);
  await modal('Choose Existing Barrier',{'Existing Barrier':addedBarrier.id},'Use Existing Barrier');await selectLibrary('import_library_item');await snapshot();assert.equal(current.physical.barriers.length,2);assert.deepEqual(current.physical.barriers[1],addedBarrier);assert.equal(current.physical.services.length,3);assert.equal(current.library_assignments.records[2].barrier_selection.choice,'existing');assert.deepEqual(current.library_assignments.records[2].barrier_selection.differences,[]);evidence.existingBarrierAddsOnlyService=true;
  // Native edit creates a real mismatch; cancellation returns to Search unchanged.
  await inspect('Barrier',addedBarrier.id);const orientationReply=page.waitForResponse(reply=>reply.url().endsWith('/physical/apply'));await details().getByLabel('Substrate orientation',{exact:true}).selectOption('Horizontal');await details().getByLabel('Substrate orientation',{exact:true}).press('Tab');assert.equal((await orientationReply).status(),200);await idle();await snapshot();const retained=structuredClone(current.physical.barriers[1]);assert.equal(retained.fields.orientation,'Horizontal');const beforeCancel=structuredClone(current);
  await appendStart('existing');await modal('Choose Existing Barrier',{'Existing Barrier':addedBarrier.id},'Use Existing Barrier');await selectLibrary();await expect(dialog().getByRole('heading',{name:'Library barrier mismatch',exact:true})).toBeVisible();await expect(dialog()).toContainText('Existing Barrier = Horizontal; selected library = Vertical');await dialog().getByRole('button',{name:'Cancel',exact:true}).click();await expect(dialog().getByRole('heading',{name:'Search Firestopping Library',exact:true})).toBeVisible();
  // Read the server directly while the dialog is open (no UI mutation or save).
  const cancelled=await page.request.get(await page.evaluate(()=>`${location.origin}/api/takeoffs/sessions/${window.CeasefireTakeoffs.sessionId()}`));assert.deepEqual((await cancelled.json()).snapshot,beforeCancel);evidence.cancelReturnsToSearchNoMutation=true;
  await selectLibrary();const mismatchReply=page.waitForResponse(reply=>reply.url().endsWith('/commands')&&reply.request().postDataJSON()?.op==='import_library_item');await modal('Library barrier mismatch',{},'Continue');assert.equal((await mismatchReply).status(),200);await snapshot();assert.equal(current.physical.defects.length,1);assert.deepEqual(current.physical.defects[0],defect);assert.equal(current.physical.barriers.length,2);assert.deepEqual(current.physical.barriers[1],retained);assert.equal(current.physical.services.length,4);const mismatch=current.library_assignments.records[3];assert.equal(mismatch.barrier_selection.mismatch_accepted,true);assert.deepEqual(mismatch.barrier_selection.differences,[{field:'orientation',selected:'Vertical',retained:'Horizontal'}]);assert.equal(mismatch.schedule_binding,null);assert.equal(current.physical.services[3].uncertainty.state,'human_review_required');assert.equal(current.physical.services[3].quantity,null);assert.deepEqual(await page.evaluate(()=>window.CeasefirePenetrations.projectSnapshot()),originalPen);evidence.continueRetainsUnapprovedMismatch=true;
  await expect(parentLabel).toContainText(current.physical.services[3].display_id);await expect(parentLabel).toContainText('Horizontal');await expect(page.locator(`.takeoff-physical-callout[data-physical-id="${addedBarrier.id}"]`)).toHaveCount(0);
  await page.screenshot({path:path.join(output,'appended-library-barriers.png')});
  // One atomic Undo preserves identities and provenance, without orphan schedule rows.
  await chooseTakeoff(page,'Steel');const undoReply=page.waitForResponse(reply=>reply.url().endsWith('/commands')&&reply.request().postDataJSON()?.op==='undo');undoReply.catch(()=>{});await page.getByRole('button',{name:'Undo last edit',exact:true}).click();assert.equal((await undoReply).status(),200);await chooseTakeoff(page,'Defect Reports');await snapshot();assert.equal(current.physical.services[3].deleted,true);assert.deepEqual(current.physical.barriers[1],retained);assert.equal(current.library_assignments.records[3].state,'needs_recheck');assert.deepEqual(current.items,[]);assert.deepEqual(await page.evaluate(()=>window.CeasefirePenetrations.projectSnapshot()),originalPen);evidence.undoRetainsIdentity=true;
  if(await page.getByRole('button',{name:'Close Item Details',exact:true}).isVisible())await page.getByRole('button',{name:'Close Item Details',exact:true}).click();const saved=structuredClone(current);const response=page.waitForResponse(reply=>new URL(reply.url()).pathname==='/api/project/save-as');response.catch(()=>{});await clickProjectControl(page,'Save');assert.equal((await response).status(),200);await expect(page.locator('#project-save-state')).toHaveText('Saved project');const project=JSON.parse(fs.readFileSync(info.project,'utf8'));assert.deepEqual(project.takeoffs.library_assignments,saved.library_assignments);
  const oldSession=await page.evaluate(()=>window.CeasefireTakeoffs.sessionId()),reopenedScan=page.waitForResponse(reply=>reply.url().endsWith('/auto-calibrate')&&!reply.url().includes(`/sessions/${oldSession}/`));reopenedScan.catch(()=>{});
  await clickProjectControl(page,'Load');await modal('Load this project?',{},'Load Project');await expect(page.locator('#project-save-state')).toHaveText('Saved project');await page.getByRole('button',{name:'Takeoffs',exact:true}).click();await chooseTakeoff(page,'Defect Reports');const scanned=await reopenedScan;assert.equal(scanned.status(),200,await scanned.text());await snapshot();assert.deepEqual(current.physical,saved.physical);assert.deepEqual(current.library_assignments,saved.library_assignments);evidence.projectRoundtrip=true;
  const pdf=path.join(output,'appended-library-barriers.pdf'),download=page.waitForEvent('download');await page.evaluate(()=>window.CeasefireTakeoffs.downloadDrawing());await(await download).saveAs(pdf);assert.ok(fs.statSync(pdf).size>1000);evidence.markedPdf=true;
  const extracted=spawnSync(process.env.CEASEFIRE_PYTHON||'python',['-c','from pypdf import PdfReader; import sys; print("".join(page.extract_text() or "" for page in PdfReader(sys.argv[1]).pages))',pdf],{cwd:root,windowsHide:true,encoding:'utf8',maxBuffer:10*1024*1024});assert.equal(extracted.status,0,extracted.stderr);const text=extracted.stdout.replace(/\s/g,'');for(const service of current.physical.services.filter(value=>!value.deleted))assert.equal(text.split(service.display_id).length-1,1,`${service.display_id} appears exactly once in the parent PDF label`);evidence.pdfCombinedLabelContainsEveryServiceOnce=true;
  assert.deepEqual(current.physical.defects[0].annotation,defect.annotation);assert.deepEqual(current.physical.barriers[0],initialBarrier);assert.equal(hash(source),sourceHash);assert.equal(hash(info.fixture),pdfHash);assert.deepEqual(await page.evaluate(()=>window.CeasefireCalculators.projectSnapshot()),calculators);assert.deepEqual(await page.evaluate(()=>window.CeasefirePenetrations.projectSnapshot()),originalPen);assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(output,'result.json'),JSON.stringify({status:'PASS',port:info.port,errors,evidence,defectId:defect.id,barrierId:addedBarrier.id,sourceSha256:sourceHash,pdfSha256:pdfHash},null,2));console.log(`PASS library barrier import native acceptance: ${output}`);
})().catch(async error=>{console.error(error.stack);console.error(logs);if(page){await page.screenshot({path:path.join(output,'failure.png')}).catch(()=>{});const diagnostic=await page.evaluate(()=>({desktop:window.CeasefireDesktop.status(),busyNodes:[...document.querySelectorAll('dialog[open], [aria-busy="true"]')].map(el=>({tag:el.tagName,id:el.id,class:el.className,hidden:!!el.closest('[hidden]'),text:el.textContent.slice(0,300)})),takeoffs:window.CeasefireTakeoffs.hasPendingOperation()})).catch(()=>null);fs.writeFileSync(path.join(output,'failure-state.json'),JSON.stringify(diagnostic,null,2));}process.exitCode=1;}).finally(async()=>{await browser?.close();server.kill();});
