"use strict";
// Native library facets and explicit many-reference linking. All state is synthetic.
const {chromium,expect}=require('@playwright/test');
const {spawn}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{createHash}=require('node:crypto');
const {chooseLibrary}=require('./section_navigation.cjs');
const root=path.resolve(__dirname,'../..'),output=path.join(root,'.runtime/browser-qa',`library-link-picker-${Date.now()}`);
const server=spawn(process.env.CEASEFIRE_PYTHON||'python',[path.join(__dirname,'library_link_picker_fixture.py'),'--directory',output],{cwd:root,windowsHide:true});
const applicationFiles=['static/libraries.js','static/libraries.css','static/library-detail-text.js','static/icons/takeoff-transfer.png','estimator/reference_library.py','estimator/firestopping_library.py','tests/browser/library_link_picker.cjs','tests/browser/library_link_picker_fixture.py'];
const hash=file=>createHash('sha256').update(fs.readFileSync(file)).digest('hex'),sourceBindings=Object.fromEntries(applicationFiles.map(file=>[file,hash(path.join(root,file))]));
let browser,page,info,logs='';const evidence={},errors=[],queries=[],linkBodies=[];
server.stderr.on('data',data=>logs+=data);
const ready=new Promise((resolve,reject)=>{let line='';const timer=setTimeout(()=>reject(new Error(`Fixture startup: ${logs}`)),120000);server.stdout.on('data',value=>{line+=value;if(line.includes('\n')){clearTimeout(timer);try{resolve(JSON.parse(line.split('\n')[0]));}catch(error){reject(error);}}});server.once('error',error=>{clearTimeout(timer);reject(error);});server.once('exit',code=>{clearTimeout(timer);reject(new Error(`Fixture exited ${code}: ${logs}`));});});
const picker=()=>page.locator('.library-link-picker:visible');
const choices=()=>picker().locator('[data-library-link-choice]');
const keys=['report','substrate','orientation','manufacturer','category','services','frl'];
const chosen={report:'Synthetic report & / fixture',substrate:'Concrete/masonry wall',orientation:'Vertical',manufacturer:'Synthetic manufacturer',category:'Plumbing & Hydraulic',services:'Copper Pipes',frl:'-/120/120'};
async function request(pathname){const response=await page.request.get(`http://127.0.0.1:${info.port}${pathname}`);assert.equal(response.status(),200,await response.text());return response.json();}
async function idlePicker(){await expect(picker().locator('.library-link-results')).toHaveAttribute('aria-busy','false');}
async function snapshots(){return page.evaluate(async()=>{await window.CeasefirePenetrations.completeProjectSnapshot();await window.CeasefireCalculators.completeProjectSnapshot();return{penetration:window.CeasefirePenetrations.projectSnapshot(),calculators:window.CeasefireCalculators.projectSnapshot()};});}
async function facetDefinitions(scope,attribute){return scope.locator(`select[${attribute}]`).evaluateAll(elements=>elements.map(el=>({key:el.getAttribute([...el.attributes].find(attr=>attr.name.startsWith('data-library-')&&attr.name.endsWith('filter')).name),options:[...el.options].slice(1).map(option=>({value:option.value,label:option.textContent}))})));}
async function filter(key,value){const reply=page.waitForResponse(response=>{const url=new URL(response.url());return url.pathname==='/api/libraries/technical'&&url.searchParams.get(key)===value&&url.searchParams.get('limit')==='20';});reply.catch(()=>{});await picker().locator(`[data-library-link-filter="${key}"]`).selectOption(value);assert.equal((await reply).status(),200);await idlePicker();}
async function search(value){const reply=page.waitForResponse(response=>{const url=new URL(response.url());return url.pathname==='/api/libraries/technical'&&url.searchParams.get('search')===value&&url.searchParams.get('limit')==='20';});reply.catch(()=>{});await picker().getByLabel('Search Technical Library',{exact:true}).fill(value);assert.equal((await reply).status(),200);await idlePicker();}
async function sameDrafts(before){assert.deepEqual(await snapshots(),before);}
(async()=>{
  info=await ready;assert.notEqual(info.port,8765);assert.equal(path.resolve(info.directory),output);const index=path.join(info.library,'library.json'),indexHash=hash(index),diagramHash=hash(path.join(info.library,'images/diagram-a.png'));
  browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1146,height:764}});page.setDefaultTimeout(30000);page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{const url=new URL(request.url());if(url.pathname==='/api/libraries/technical'&&url.searchParams.get('limit')==='20')queries.push(Object.fromEntries(url.searchParams));if(request.method()==='POST'&&url.pathname.endsWith('/links'))linkBodies.push(request.postDataJSON());});
  await page.goto(`http://127.0.0.1:${info.port}/`);await page.waitForFunction(()=>window.CeasefireDesktop?.status().ready&&!window.CeasefireDesktop.status().busy);
  const before=await snapshots(),saveState=await page.locator('#project-save-state').textContent();
  await chooseLibrary(page,'technical');const technical=page.locator('#technical-library-workspace');await expect(technical.locator('[data-library-filter="report"]')).toBeVisible();const nativeFacets=await facetDefinitions(technical,'data-library-filter');
  await chooseLibrary(page,'penetration');const library=page.locator('#penetration-library-workspace');const card=library.locator('.library-result').filter({has:page.locator(`[data-library-link="${info.item_id}"]`)});
  const transfer=card.getByRole('button',{name:'Add to Schedule',exact:true});await expect(transfer).toBeVisible();const image=transfer.locator('img');await expect(image).toHaveAttribute('src','/icons/takeoff-transfer.png');await expect(image).toHaveAttribute('aria-hidden','true');assert.equal(await image.getAttribute('alt'),'');await expect.poll(()=>image.evaluate(el=>el.complete&&el.naturalWidth===512&&el.naturalHeight===512)).toBe(true);
  const icon=await page.request.get(`http://127.0.0.1:${info.port}/icons/takeoff-transfer.png`);assert.equal(icon.status(),200);assert.equal(createHash('sha256').update(await icon.body()).digest('hex'),'1b5552f06a1cb61d246e969f70a5243883a8ba6b1ddaa5392ddd737d802f1d1b');evidence.originalIconBytes=true;
  evidence.transferLayouts=[];for(const width of [1146,752,390]){await page.setViewportSize({width,height:764});await transfer.scrollIntoViewIfNeeded();const metrics=await transfer.evaluate(el=>{const s=getComputedStyle(el),image=el.querySelector('img').getBoundingClientRect(),b=el.getBoundingClientRect();return{width:b.width,height:b.height,radius:s.borderRadius,border:s.borderWidth,padding:s.padding,imageWidth:image.width,imageHeight:image.height,overflow:document.documentElement.scrollWidth-innerWidth};});assert.equal(metrics.width,38);assert.equal(metrics.height,38);assert.equal(metrics.radius,'9px');assert.equal(metrics.border,'1px');assert.equal(metrics.padding,'8px');assert.equal(metrics.imageWidth,24);assert.equal(metrics.imageHeight,24);assert.ok(metrics.overflow<=1);evidence.transferLayouts.push({width,...metrics});}
  await page.setViewportSize({width:1146,height:764});await card.getByRole('button',{name:'Link Library Item',exact:true}).click();await idlePicker();await expect(choices()).toHaveCount(20);
  const pickerFacets=await facetDefinitions(picker(),'data-library-link-filter');assert.deepEqual(pickerFacets.map(value=>value.key),keys);for(const facet of pickerFacets)assert.deepEqual(facet.options,nativeFacets.find(value=>value.key===facet.key).options);evidence.existingApiFacetsExactly=true;
  await picker().locator('[data-library-link-choice="technical-001"]').check();for(const key of keys)await filter(key,chosen[key]);await expect(choices()).toHaveCount(20);assert.equal(queries.at(-1).offset,'0');for(const key of keys)assert.equal(queries.at(-1)[key],chosen[key]);await expect(picker().locator('[data-library-link-choice="technical-001"]')).toBeChecked();
  const next=page.waitForResponse(response=>{const u=new URL(response.url());return u.pathname==='/api/libraries/technical'&&u.searchParams.get('offset')==='20'&&u.searchParams.get('limit')==='20';});await picker().getByRole('button',{name:'Next',exact:true}).click();assert.equal((await next).status(),200);await idlePicker();await expect(choices()).toHaveCount(20);await picker().locator('[data-library-link-choice="technical-021"]').check();for(const key of keys)assert.equal(queries.at(-1)[key],chosen[key]);
  await search('Synthetic & /');await expect(picker().locator('[data-library-link-choice="technical-001"]')).toBeChecked();assert.equal(queries.at(-1).offset,'0');await picker().getByRole('button',{name:'Clear filters',exact:true}).click();await idlePicker();for(const key of keys)assert.equal(queries.at(-1)[key],undefined);assert.equal(queries.at(-1).search,'');
  await search('045');await expect(choices()).toHaveCount(1);await picker().locator('[data-library-link-choice="technical-045"]').check();await picker().getByRole('button',{name:'Clear filters',exact:true}).click();await idlePicker();await expect(picker().locator('[data-library-link-choice="technical-001"]')).toBeChecked();await expect(picker().getByRole('button',{name:'Save links (3)',exact:true})).toBeEnabled();await sameDrafts(before);assert.equal(await page.locator('#project-save-state').textContent(),saveState);evidence.selectionAcrossFiltersPagesSearchClear=true;
  evidence.pickerLayouts=[];for(const width of [1146,752,390]){await page.setViewportSize({width,height:764});await picker().getByRole('heading',{name:'Link Library Item',exact:true}).scrollIntoViewIfNeeded();const geometry=await picker().evaluate(el=>({overflow:document.documentElement.scrollWidth-innerWidth,facets:[...el.querySelectorAll('[data-library-link-filter]')].map(select=>{const b=select.getBoundingClientRect();return{key:select.dataset.libraryLinkFilter,x:b.x,right:b.right,width:b.width};})}));assert.ok(geometry.overflow<=1);assert.equal(geometry.facets.length,7);assert.ok(geometry.facets.every(f=>f.x>=-1&&f.right<=width+1));await page.screenshot({path:path.join(output,`picker-${width}.png`),fullPage:true});evidence.pickerLayouts.push({width,...geometry});}
  await page.setViewportSize({width:1146,height:764});const saved=page.waitForResponse(response=>new URL(response.url()).pathname===`/api/libraries/penetration/${info.item_id}/links`&&response.request().method()==='POST');await picker().getByRole('button',{name:'Save links (3)',exact:true}).focus();await page.keyboard.press('Enter');const reply=await saved;assert.equal(reply.status(),200,await reply.text());const receipt=await reply.json();assert.equal(receipt.linked,true);const selected=['technical-001','technical-021','technical-045'];assert.deepEqual(receipt.technical_ids,selected);assert.deepEqual(linkBodies,[{technical_ids:selected}]);await expect(picker()).toHaveCount(0);
  const linked=await request(`/api/libraries/penetration/${info.item_id}`);assert.deepEqual(linked.links.map(link=>link.id),selected);for(const id of selected){const reverse=await request(`/api/libraries/technical/${id}`);assert.ok(reverse.links.some(link=>link.id===info.item_id&&link.kind==='penetration'));}evidence.exactMultiReferenceReceiptAndReciprocalLinks=true;
  await sameDrafts(before);assert.equal(await page.locator('#project-save-state').textContent(),saveState);assert.equal(hash(index),indexHash);assert.equal(hash(path.join(info.library,'images/diagram-a.png')),diagramHash);assert.deepEqual(errors,[]);assert.deepEqual(Object.fromEntries(applicationFiles.map(file=>[file,hash(path.join(root,file))])),sourceBindings);
  fs.writeFileSync(path.join(output,'result.json'),JSON.stringify({passed:true,evidence,queries,linkBodies,errors,sourceBindings,sourceIndexSHA256:indexHash,diagramSHA256:diagramHash,limits:['Synthetic reference library and disposable database only; no existing browser drafts or live application were inspected.']},null,2));console.log(JSON.stringify({passed:true,output,evidence}));
})().catch(async error=>{if(page)await page.screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{});fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'failure.json'),JSON.stringify({passed:false,error:error.stack,evidence,queries,linkBodies,errors,sourceBindings},null,2));console.error(error);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.kill();fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'server.log'),logs);});
