// Rendered physical-register acceptance. The fixture owns every record and save target.
const { chromium, expect } = require('@playwright/test');
const { spawn } = require('node:child_process');
const { randomUUID } = require('node:crypto');
const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict');
const root=path.resolve(__dirname,'../..'), output=path.join(root,'.runtime/browser-qa',`physical-register-${Date.now()}`);
fs.mkdirSync(output,{recursive:true});
const server=spawn(process.env.CEASEFIRE_PYTHON||'python',[path.join(__dirname,'fixtures.py'),'--directory',output],{cwd:root,windowsHide:true});
let logs='',browser,page,state,origin;
server.stderr.on('data',value=>{logs+=value;});
const ready=new Promise((resolve,reject)=>{let stdout='';const timer=setTimeout(()=>reject(new Error(`Startup timeout: ${logs}`)),120000);server.stdout.on('data',data=>{stdout+=data;if(stdout.includes('\n')){clearTimeout(timer);try{resolve(JSON.parse(stdout.split('\n')[0]));}catch(error){reject(error);}}});server.once('error',reject);server.once('exit',code=>{clearTimeout(timer);reject(new Error(`Server exited ${code}: ${logs}`));});});
const errors=[], previews=[], checks={};
const physical=()=>state.snapshot.physical;
const record=id=>['defects','barriers','services'].flatMap(kind=>physical()[kind]).find(entry=>entry.id===id);
const inspector=()=>page.getByRole('complementary',{name:'Item Details'});
const row=id=>page.locator(`tr[data-physical-id="${id}"]`);
const all=()=>page.getByRole('checkbox',{name:'Select all matching physical records',exact:true});
const filter=()=>page.getByLabel('Filter physical hierarchy',{exact:true});
async function idle(){await expect(page.locator('#takeoffs-workspace')).not.toHaveAttribute('aria-busy','true');await expect(page.locator('.takeoff-physical-register')).not.toHaveAttribute('aria-busy','true');}
async function response(action,suffix){const wait=page.waitForResponse(reply=>new URL(reply.url()).pathname.endsWith(suffix));wait.catch(()=>{});await action();const reply=await wait,result=await reply.json();assert.equal(reply.status(),200,JSON.stringify(result));return result;}
async function fill(scope,values){for(const[label,value]of Object.entries(values)){const control=scope.getByLabel(label,{exact:true});if(await control.evaluate(el=>el.tagName)==='SELECT')await control.selectOption(String(value));else await control.fill(String(value));}}
async function dialog(title,values,submit){const modal=page.getByRole('dialog');await expect(modal.getByRole('heading',{name:title,exact:true})).toBeVisible({timeout:30000});await fill(modal,values);await modal.getByRole('button',{name:submit,exact:true}).click();}
async function apply(title){
 state=await response(async()=>{
  const modal=page.getByRole('dialog');await expect(modal.getByRole('heading',{name:title,exact:true})).toBeVisible();
  const navigation=modal.getByLabel('Review navigation',{exact:true});
  if(await navigation.count()){
   await dialog(title,{'Review navigation':'next'},'Continue');await expect(navigation.locator('option[value=previous]')).toHaveCount(1);await expect(modal).toContainText('Showing 101–105 of 105 relationship impacts');
   await dialog(title,{'Review navigation':'apply'},'Continue');
  }else await dialog(title,{},'Apply draft change');
 },'/physical/apply');await idle();return state;
}
async function create(kind,values,trigger){await page.getByRole('button',{name:trigger||`Add ${kind}`,exact:true}).click();const preview=await response(()=>dialog(`Create draft ${kind}`,values,'Preview new draft'),'/physical/preview');await apply(`Create one draft ${kind}?`);return preview.changed_ids[0];}
async function select(id){await row(id).locator('.takeoff-row-link').click();await idle();}
async function snapshot(){const session=await page.evaluate(()=>window.CeasefireTakeoffs.sessionId());const reply=await page.request.get(`${origin}/api/takeoffs/sessions/${session}`);assert.equal(reply.status(),200);return reply.json();}
async function fixture(commands){ // Seed only scale/retained-value cases through the validated API.
  state=await snapshot();const session=await page.evaluate(()=>window.CeasefireTakeoffs.sessionId());
  const previewReply=await page.request.post(`${origin}/api/takeoffs/sessions/${session}/physical/preview`,{data:{expected_revision:state.revision,commands}});assert.equal(previewReply.status(),200,await previewReply.text());const preview=await previewReply.json();
  const reply=await page.request.post(`${origin}/api/takeoffs/sessions/${session}/physical/apply`,{data:{expected_revision:preview.revision,request_id:randomUUID(),preview_id:preview.preview_id}});assert.equal(reply.status(),200,await reply.text());state=await reply.json();
  await page.evaluate(async()=>{const t=window.CeasefireTakeoffs; t.applyProject(await t.prepareProject(t.projectSnapshot(),t.sessionId()));await t.open();});await idle();
}
async function choices(control,expected){assert.equal(await control.evaluate(el=>el.tagName),'SELECT');assert.deepEqual(await control.locator('option').evaluateAll(options=>options.map(option=>option.value).filter(Boolean)),expected);}
async function selected(n){await expect(page.locator('.takeoff-physical-register .takeoff-register-controls strong')).toHaveText(`${n} selected`);}
async function restore(id,kind){await select(id);await page.getByRole('button',{name:'Restore draft record',exact:true}).click();await response(()=>dialog(`Restore draft ${kind}`,{'Restore scope':'same_deletion'},'Preview restoration'),'/physical/preview');await apply('Review retained identities to restore');}
(async()=>{
 const info=await ready;assert.notEqual(info.port,8765);origin=`http://127.0.0.1:${info.port}`;
 browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1146,height:764},deviceScaleFactor:1});page.setDefaultTimeout(30000);
 page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(request.url().endsWith('/physical/preview'))previews.push(request.postDataJSON());});
 await page.goto(origin);await expect.poll(()=>page.evaluate(()=>window.CeasefireDesktop?.status().ready)).toBe(true);
 const calculatorBefore=await page.evaluate(()=>window.CeasefireCalculators.completeProjectSnapshot());
 const definitionReply=await page.request.post(`${origin}/api/penetration/definition`,{data:{configuration:await page.evaluate(()=>window.CeasefireProject.configuration())}});assert.equal(definitionReply.status(),200);const definition=await definitionReply.json(),frls=definition.row_fields.find(field=>field.column==='N').options;
 await page.getByRole('button',{name:'Takeoffs',exact:true}).click();await page.locator('[data-mode="physical"]').click();await idle();
 for(const name of ['Undo physical / takeoff edit','Physical / takeoff audit history','Add barrier','Add service'])await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0);
 await expect(all()).toBeDisabled();
 await page.getByRole('button',{name:'Add defect',exact:true}).click();await expect(page.getByRole('heading',{name:'Create draft defect',exact:true})).toBeVisible();await expect(page.getByRole('dialog').getByLabel('Defect label',{exact:true})).toHaveCount(0);await choices(page.getByRole('dialog').getByLabel('FRL',{exact:true}),frls);
 const created=await response(()=>dialog('Create draft defect',{'Defect Ref.':'REFERENCE-1','FRL':'-/120/120'},'Preview new draft'),'/physical/preview');await apply('Create one draft defect?');const defect=created.changed_ids[0];assert.equal(record(defect).fields.label,'REFERENCE-1');await choices(inspector().getByLabel('FRL',{exact:true}),frls);await choices(page.getByLabel('FRL for REFERENCE-1',{exact:true}),frls);
 const barrier=await create('barrier',{'Barrier type':'Core hole'},'Add barrier to D-0001');
 const service=await create('service',{'Category':'Mechanical','Service type':definition.row_fields.find(field=>field.column==='K').options[0],'Explicit service quantity':2,'Width x Height (mm)':'100 x 75','Overall Diameter (mm)':25},'Add service to B-0001');
 assert.equal(record(service).fields.width_mm,100);assert.equal(record(service).fields.height_mm,75);assert.equal(record(service).fields.diameter_mm,25);assert.ok(!Object.hasOwn(record(service).fields,'width_height_mm'));
 for(const label of ['Width (mm)','Height (mm)','Diameter (mm)'])await expect(inspector().getByLabel(label,{exact:true})).toHaveCount(0);
 const layout=await page.locator('.takeoff-physical-add-row').evaluate(el=>({previous:el.previousElementSibling.className,next:el.nextElementSibling.className,text:el.querySelector('button').textContent,width:el.querySelector('button').getBoundingClientRect().width,height:el.querySelector('button').getBoundingClientRect().height,childWidth:document.querySelector('.takeoff-physical-id-cell .takeoff-physical-add-child').getBoundingClientRect().width,childHeight:document.querySelector('.takeoff-physical-id-cell .takeoff-physical-add-child').getBoundingClientRect().height,background:getComputedStyle(el.querySelector('button')).backgroundColor,color:getComputedStyle(el.querySelector('button')).color,idColor:getComputedStyle(document.querySelector('.takeoff-physical-id-cell .takeoff-row-link')).color}));
 assert.ok(layout.previous.includes('takeoff-register-table'));assert.ok(layout.next.includes('takeoff-register-controls'));assert.equal(layout.background,layout.idColor);assert.equal(layout.color,'rgb(255, 255, 255)');assert.equal(layout.text,'+');assert.equal(layout.width,layout.childWidth);assert.equal(layout.height,layout.childHeight);
 const discard=page.getByRole('button',{name:'Discard unfinished physical edits',exact:true}),deletion=page.getByRole('button',{name:'Delete selected records',exact:true});
 for(const button of [discard,deletion]){await expect(button.locator('svg')).toHaveCount(1);assert.ok((await button.boundingBox()).width<=40);assert.equal((await button.innerText()).trim(),'');assert.deepEqual(await button.locator('svg').evaluate(el=>({fill:getComputedStyle(el).fill,stroke:getComputedStyle(el).stroke,width:getComputedStyle(el).strokeWidth})),{fill:'none',stroke:'rgb(88, 75, 83)',width:'2px'});}
 await page.getByRole('button',{name:'Collapse D-0001',exact:true}).click();await expect(page.getByRole('button',{name:'Expand D-0001',exact:true})).toHaveText('>');await expect(row(service)).toHaveCount(0);await all().check();await selected(3);await all().uncheck();await selected(0);await page.getByRole('button',{name:'Expand D-0001',exact:true}).click();await expect(page.getByRole('button',{name:'Collapse D-0001',exact:true})).toHaveText('<');checks.layout_and_disclosure=true;
 await page.locator('.takeoff-physical-register').evaluate(el=>window.scrollTo(0,window.scrollY+el.getBoundingClientRect().top-document.querySelector('.app-header').getBoundingClientRect().height-12));await page.screenshot({path:path.join(output,'register-controls-1146.png')});
 // Invalid combined dimensions cannot partially alter either canonical dimension.
 await select(service);const initialFields=structuredClone(record(service).fields),beforeInvalid=previews.length;
 await fill(inspector(),{'Width x Height (mm)':'100 x','Overall Diameter (mm)':31});await page.getByRole('button',{name:'Preview physical edits',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Width x Height');assert.equal(previews.length,beforeInvalid);state=await snapshot();assert.deepEqual(record(service).fields,initialFields);await discard.click();await expect(inspector().getByLabel('Overall Diameter (mm)',{exact:true})).toHaveValue('25');
 await fill(inspector(),{'Width x Height (mm)':'120.5 × 80','Overall Diameter (mm)':31});await response(()=>page.getByRole('button',{name:'Preview physical edits',exact:true}).click(),'/physical/preview');await apply('Review physical field changes');assert.equal(record(service).fields.width_mm,120.5);assert.equal(record(service).fields.height_mm,80);assert.equal(record(service).fields.diameter_mm,31);checks.atomic_dimensions=true;
 await fixture([{op:'update',entity_id:service,changes:{fields:{...record(service).fields,label:'Retained service'}}},{op:'update',entity_id:defect,changes:{fields:{...record(defect).fields,frl:' Historic FRL '}}}]);
 await select(defect);await expect(inspector().getByLabel('FRL',{exact:true})).toHaveValue(' Historic FRL ');await fill(inspector(),{'Notes':'Keep historical FRL'});await response(()=>page.getByRole('button',{name:'Preview physical edits',exact:true}).click(),'/physical/preview');await apply('Review physical field changes');assert.equal(record(defect).fields.frl,' Historic FRL ');checks.retained_frl=true;
 // Header selection includes filter matches across pages, excludes contextual parents,
 // and includes children hidden by a collapsed parent when there is no text filter.
 const more=Array.from({length:103},(_,i)=>({op:'create',kind:'service',entity:{id:randomUUID(),barrier_id:barrier,quantity:1,fields:{notes:`BATCH-SERVICE ${i<2?'DELETE-ME':'KEEP-ME'}`},evidence:[],uncertainty:{state:'not_assessed',note:''}}}));
 await fixture(more.slice(0,100));await fixture(more.slice(100));await filter().fill('BATCH-SERVICE');await all().check();await selected(103);await expect(all()).toBeChecked();await page.getByRole('button',{name:'Next 100 records',exact:true}).click();await expect(all()).toBeChecked();await expect(row(defect).getByRole('checkbox')).not.toBeChecked();await expect(row(barrier).getByRole('checkbox')).not.toBeChecked();
 const last=more.at(-1).entity.id;await row(last).getByRole('checkbox').uncheck();await selected(102);assert.equal(await all().evaluate(el=>el.indeterminate),true);await all().check();await selected(103);await all().uncheck();await selected(0);
 await filter().fill('');await page.getByRole('button',{name:'Collapse D-0001',exact:true}).click();await all().check();await selected(106);await all().uncheck();await page.getByRole('button',{name:'Expand D-0001',exact:true}).click();checks.header_filter_pages_collapsed=true;
 await filter().fill('DELETE-ME');await all().check();await selected(2);const targets=more.slice(0,2).map(entry=>entry.entity.id),beforeDelete=targets.map(id=>structuredClone(record(id)));
 await response(()=>deletion.click(),'/physical/preview');await apply('Review recoverable deletion');for(const id of targets)assert.equal(record(id).deleted,true);assert.equal(record(service).deleted,false);assert.equal(record(barrier).deleted,false);await expect(all()).toBeDisabled();
 await page.getByLabel('Show deleted records',{exact:true}).check();await expect(all()).toBeDisabled();for(const id of targets)await restore(id,'service');for(let i=0;i<targets.length;i++){const restored=record(targets[i]);for(const key of ['id','display_id','barrier_id','fields','evidence','quantity'])assert.deepEqual(restored[key],beforeDelete[i][key]);assert.equal(restored.deleted,false);}checks.bulk_delete_restore=true;
 // Selecting a parent never deletes unselected descendants without the scope choice.
 await filter().fill('');await page.getByRole('button',{name:'Clear physical selection',exact:true}).click();await row(barrier).getByRole('checkbox').check();const beforeScope=previews.length;await deletion.click();await dialog('Delete 1 selected records?',{'Deletion scope':'only'},'Preview deletion');await expect(page.getByRole('alert')).toContainText('unselected active descendants');assert.equal(previews.length,beforeScope);state=await snapshot();assert.equal(record(barrier).deleted,false);assert.ok(physical().services.every(entry=>!entry.deleted));checks.descendant_scope_guard=true;
 const retainedSubtree=[record(barrier),...physical().services].map(entry=>structuredClone(entry));
 await deletion.click();await response(()=>dialog('Delete 1 selected records?',{'Deletion scope':'cascade'},'Preview deletion'),'/physical/preview');await apply('Review recoverable deletion');assert.equal(record(defect).deleted,false);assert.equal(record(barrier).deleted,true);assert.ok(physical().services.every(entry=>entry.deleted));
 await restore(barrier,'barrier');assert.ok(physical().services.every(entry=>!entry.deleted));for(const prior of retainedSubtree){const current=record(prior.id);for(const key of ['id','display_id','barrier_id','defect_id','fields','evidence','quantity'])assert.deepEqual(current[key],prior[key]);}checks.explicit_cascade_restores_subtree=true;
 // Save As and Save flush the pending inspector through the ordinary review and persist it.
 await select(service);await fill(inspector(),{'Notes':'Pending physical note saved by Save As'});
 const saveWait=page.waitForResponse(reply=>new URL(reply.url()).pathname==='/api/project/save-as');saveWait.catch(()=>{});await page.getByRole('button',{name:'Save As',exact:true}).click();await apply('Review physical field changes');assert.equal((await saveWait).status(),200);await expect(page.locator('#project-save-state')).toHaveText('Saved project');let saved=JSON.parse(fs.readFileSync(info.project,'utf8'));assert.equal(saved.takeoffs.physical.services.find(entry=>entry.id===service).fields.notes,'Pending physical note saved by Save As');
 await select(service);await fill(inspector(),{'Notes':'Pending physical note saved by Save'});const directSave=page.waitForResponse(reply=>new URL(reply.url()).pathname==='/api/project/save');directSave.catch(()=>{});await page.getByRole('button',{name:'Save',exact:true}).click();await apply('Review physical field changes');assert.equal((await directSave).status(),200);await expect(page.locator('#project-save-state')).toHaveText('Saved project');saved=JSON.parse(fs.readFileSync(info.project,'utf8'));const savedPhysical=saved.takeoffs.physical;
 await response(()=>page.getByRole('button',{name:'Load',exact:true}).click(),'/api/project/open');await page.getByRole('dialog').getByRole('button',{name:'Load Project',exact:true}).click();await expect(page.locator('#project-save-state')).toHaveText('Saved project');await page.getByRole('button',{name:'Takeoffs',exact:true}).click();await page.locator('[data-mode="physical"]').click();state=await snapshot();assert.deepEqual(physical(),savedPhysical);await select(service);await expect(inspector().getByLabel('Notes',{exact:true})).toHaveValue('Pending physical note saved by Save');await expect(inspector().getByLabel('Width x Height (mm)',{exact:true})).toHaveValue('120.5 x 80');assert.equal(record(service).fields.label,'Retained service');assert.equal(record(defect).fields.frl,' Historic FRL ');checks.pending_save_save_as_reopen=true;
 await inspector().screenshot({path:path.join(output,'service-fields-reopened.png')});await page.locator('.takeoff-physical-register').screenshot({path:path.join(output,'physical-register.png')});await filter().fill('REFERENCE-1');await page.locator('.takeoff-physical-register').evaluate(el=>window.scrollTo(0,window.scrollY+el.getBoundingClientRect().top-document.querySelector('.app-header').getBoundingClientRect().height-12));await page.screenshot({path:path.join(output,'reopened-filtered-register-1146.png')});
 assert.deepEqual(await page.evaluate(()=>window.CeasefireCalculators.completeProjectSnapshot()),calculatorBefore);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'result.json'),JSON.stringify({completed:true,checks,ids:{defect,barrier,service},frl_choices:frls,total_services:physical().services.length,errors},null,2));console.log(`PASS: physical register layout, exact FRL choices, atomic dimensions, selection across pages/filter/collapse, recoverable deletion and pending Save/Save As/reopen. Evidence: ${output}`);
})().catch(async error=>{console.error(error);console.error(logs.slice(-3000));if(page){await page.screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{});fs.writeFileSync(path.join(output,'failure.txt'),await page.locator('body').innerText().catch(()=>''));}process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(output,'server.log'),logs);if(browser)await browser.close();server.kill();});
