"use strict";
// Private signature ink is generated by this fixture. Original PDFs, projects,
// browser storage and server state are disposable and never use production 8765.
const { chromium, expect } = require("@playwright/test");
const { chooseTakeoff } = require("./section_navigation.cjs"), { clickProjectControl } = require("./project_actions.cjs");
const { renderDrawing } = require("./viewer_helpers.cjs"), { settingsSettled } = require("./settings_helpers.cjs");
const { spawn, spawnSync } = require("node:child_process");
const fs = require("node:fs"), path = require("node:path"), crypto = require("node:crypto"), assert = require("node:assert/strict");
const root = path.resolve(__dirname, "../.."), output = path.join(root, ".runtime/browser-qa", `signatures-${Date.now()}`), python = process.env.CEASEFIRE_PYTHON || "python";
fs.mkdirSync(output, { recursive: true });
const assets = ["static/takeoffs.js", "static/takeoff-signatures.js", "static/takeoffs.css", "estimator/takeoff_signatures.py", "estimator/takeoff_markup_pdf_worker.py", "tests/browser/signatures.cjs"];
const hash = file => crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex");
const hashes = () => Object.fromEntries(assets.map(name => [name, hash(path.join(root, name))]));
const sourceBefore = hashes(), checks = [], errors = [], requests = [], projectWrites = [], pdfExports = [];
const check = name => { checks.push(name); console.log(`ok - ${name}`); };
const server = spawn(python, [path.join(__dirname, "fixtures.py"), "--directory", output], { cwd: root, windowsHide: true });
let browser, page, logs = ""; server.stderr.on("data", value => { logs += value; });
const ready = new Promise((resolve, reject) => {
  let stdout = ""; const timer = setTimeout(() => reject(new Error(`Fixture startup timeout: ${logs}`)), 120000);
  server.stdout.on("data", value => { stdout += value; if (stdout.includes("\n")) { clearTimeout(timer); try { resolve(JSON.parse(stdout.split("\n")[0])); } catch (error) { reject(error); } } });
  server.once("error", error => { clearTimeout(timer); reject(error); }); server.once("exit", code => { clearTimeout(timer); reject(new Error(`Fixture exited ${code}: ${logs}`)); });
});
const panel = () => page.locator("#takeoff-markup-settings"), signature = id => page.locator(`.takeoff-signature[data-signature-id="${id}"]`);
const idle = () => settingsSettled(page);
async function snapshot() { await idle(); return page.evaluate(() => window.CeasefireTakeoffs.projectSnapshot()); }
async function command(action, op) {
  const pending = page.waitForResponse(reply => reply.url().endsWith("/commands") && reply.request().postDataJSON()?.op === op); pending.catch(() => {});
  await action(); const reply = await pending, value = await reply.json(); assert.equal(reply.status(), 200, JSON.stringify(value)); await idle(); return value;
}
async function fit() { await renderDrawing(page, () => page.getByRole("button", { name: "Fit page", exact: true }).click()); await idle(); }
async function screen([x, y]) {
  const overlay = page.locator(".takeoff-overlay"); await overlay.scrollIntoViewIfNeeded();
  await overlay.evaluate(el => window.scrollTo(0, window.scrollY + el.getBoundingClientRect().top - 190));
  const box = await overlay.boundingBox(), point = [box.x + x / 842 * box.width, box.y + (595 - y) / 595 * box.height];
  assert.equal(await page.evaluate(([a, b]) => !!document.elementFromPoint(a, b)?.closest(".takeoff-overlay"), point), true, "Pointer reaches the synthetic source page"); return point;
}
function invariant(current, baseline) {
  for (const key of ["documents", "items", "calibrations", "transfers", "physical", "service_plans", "image_extractions", "annotations"])
    assert.deepEqual(current[key], baseline[key], `Signature operations preserve ${key}`);
}
async function fillDialog(title, values, submit) {
  const modal = page.getByRole("dialog"); await expect(modal.getByRole("heading", { name: title, exact: true })).toBeVisible();
  for (const [name, value] of Object.entries(values)) { const field = modal.getByLabel(name, { exact: true });
    if (await field.evaluate(el => el.tagName) === "SELECT") await field.selectOption(String(value)); else await field.fill(String(value)); }
  await modal.getByRole("button", { name: submit, exact: true }).click(); await expect(page.locator("dialog.takeoff-dialog")).toHaveCount(0);
}
async function padDraw(replacement = false) {
  const modal = page.getByRole("dialog", { name: "Signatures", exact: true }); await expect(modal).toBeVisible();
  await modal.getByRole("button", { name: "Clear pad", exact: true }).click(); const box = await modal.getByLabel("Signature drawing pad", { exact: true }).boundingBox();
  const strokes = replacement ? [[[.1, .75], [.28, .15], [.45, .7], [.65, .15], [.9, .7]], [[.1, .85], [.9, .85]]]
    : [[[.1, .5], [.22, .12], [.35, .75], [.48, .25], [.65, .65], [.87, .3]], [[.12, .84], [.88, .84]]];
  for (const stroke of strokes) { await page.mouse.move(box.x + stroke[0][0] * box.width, box.y + stroke[0][1] * box.height); await page.mouse.down();
    for (const [x, y] of stroke.slice(1)) await page.mouse.move(box.x + x * box.width, box.y + y * box.height, { steps: 3 }); await page.mouse.up(); }
  await expect(modal.getByRole("button", { name: "Insert signature", exact: true })).toBeEnabled();
  await modal.getByRole("button", { name: "Insert signature", exact: true }).click(); await expect(modal).toHaveCount(0);
}
async function insert(point, reuse = false) {
  await page.getByRole("button", { name: "Signatures", exact: true }).click();
  if (reuse) { const modal = page.getByRole("dialog", { name: "Signatures", exact: true }); await expect(modal.getByRole("img", { name: "Saved signature preview", exact: true })).toBeVisible();
    await modal.getByRole("button", { name: "Use saved signature", exact: true }).click(); await expect(modal).toHaveCount(0); }
  else await padDraw();
  await expect(page.locator(".takeoff-viewport")).toHaveAttribute("data-tool", "signature");
  const result = await command(async () => page.mouse.click(...await screen(point)), "create_signature");
  const record = result.snapshot.signatures.records.find(value => value.id === result.created_signature_id);
  await expect(signature(record.id)).toBeVisible(); await expect(panel().getByRole("heading", { name: "Signature Settings", exact: true })).toBeVisible();
  return { record, result };
}
async function select(id) {
  await page.getByRole("button", { name: "Select", exact: true }).click(); await signature(id).press("Enter");
  await expect(panel().getByRole("heading", { name: "Signature Settings", exact: true })).toBeVisible(); await idle();
}
async function drag(target, dx, dy) {
  await target.scrollIntoViewIfNeeded(); const box = await target.boundingBox(), start = [box.x + box.width / 2, box.y + box.height / 2];
  assert.equal(await page.evaluate(([x, y]) => !!document.elementFromPoint(x, y)?.closest(".takeoff-signature"), start), true, "Pointer reaches signature");
  await page.mouse.move(...start); await page.mouse.down(); await page.mouse.move(start[0] + dx, start[1] + dy, { steps: 8 }); await page.mouse.up();
}
async function download(name, expectedIds, physicalScope = null) {
  const before = await snapshot(), pending = page.waitForEvent("download"), request = page.waitForRequest(value => value.url().endsWith("/export/marked-pdf"));
  await page.evaluate(() => window.CeasefireTakeoffs.downloadDrawing()); const file = await pending, target = path.join(output, name);
  assert.equal(await file.failure(), null); await file.saveAs(target); const body = (await request).postDataJSON(); await idle();
  assert.deepEqual(body.signature_ids, expectedIds); if (physicalScope) { assert.equal(body.mode, "penetrations"); assert.equal(body.physical_scope, physicalScope); }
  else assert.equal(body.mode, "walls_floors");
  assert.deepEqual(await snapshot(), before, "PDF export is read-only");
  const records = before.signatures.records.filter(value => expectedIds.includes(value.id));
  const spec = path.join(output, `${name}.json`); fs.writeFileSync(spec, JSON.stringify({ records, document: before.documents.find(doc => doc.id === body.document_id), physical: !!physicalScope }));
  const pythonScript = [
    "import json,sys,math", "from pypdf import PdfReader", "from pypdf.generic import ContentStream", "from estimator.takeoff_markup_pdf_worker import page_transform,transform",
    "r=PdfReader(sys.argv[1]);s=json.load(open(sys.argv[2],encoding='utf-8'));matches=[]",
    "for sig in s['records']:", " p=r.pages[sig['page']-1];meta=next(x for x in s['document']['pages'] if x['page']==sig['page'])",
    " _,w,h=page_transform(meta);bottom=0 if s['physical'] else float(p.mediabox.height)-h;matrix,_,_=page_transform(meta,bottom,(float(p.mediabox.width)-w)/2)",
    " ops=[(op.decode(),[float(n) for n in args]) for args,op in ContentStream(p.get_contents(),r).operations if op in (b'm',b'l')]",
    " q0,q1,_,q3=sig['quad_pdf'];count=0", " for stroke in sig['strokes']:",
    "  expected=[('m' if i==0 else 'l',transform([q0[a]+x*(q1[a]-q0[a])+y*(q3[a]-q0[a]) for a in (0,1)],matrix)) for i,(x,y) in enumerate(stroke)]",
    "  found=any(all(a[0]==b[0] and len(a[1])==2 and all(abs(a[1][j]-b[1][j])<0.0001 for j in (0,1)) for a,b in zip(ops[start:start+len(expected)],expected)) for start in range(len(ops)-len(expected)+1))",
    "  assert found,'Signature vector stroke absent from actual PDF';count+=1", " matches.append({'id':sig['id'],'vector_strokes':count})",
    "print(json.dumps({'pages':len(r.pages),'matches':matches,'sha256':__import__('hashlib').sha256(open(sys.argv[1],'rb').read()).hexdigest()}))"
  ].join("\n");
  const inspected = spawnSync(python, ["-X", "utf8", "-B", "-c", pythonScript, target, spec], { cwd: root, windowsHide: true, encoding: "utf8" });
  assert.equal(inspected.status, 0, inspected.stderr); const proof = JSON.parse(inspected.stdout); pdfExports.push({ file: target, body, proof }); return proof;
}
async function saveLoad(info) {
  const before = await snapshot(), saving = page.waitForResponse(reply => reply.url().endsWith("/api/project/save-as")); saving.catch(() => {});
  await clickProjectControl(page, "Save"); assert.equal((await saving).status(), 200); await expect(page.locator("#project-save-state")).toHaveText("Saved project");
  const saved = JSON.parse(fs.readFileSync(info.project, "utf8")); assert.deepEqual(saved.takeoffs.signatures, before.signatures);
  const opening = page.waitForResponse(reply => reply.url().endsWith("/api/project/open")); opening.catch(() => {}); await clickProjectControl(page, "Load");
  assert.equal((await opening).status(), 200); await page.getByRole("dialog").getByRole("button", { name: "Load Project", exact: true }).click();
  await expect(page.locator("#project-save-state")).toHaveText("Saved project"); await page.getByRole("button", { name: "Takeoffs", exact: true }).click();
  await chooseTakeoff(page, "wall"); const after = await snapshot(); assert.deepEqual(after.signatures, before.signatures); invariant(after, before); return after;
}
async function armedPlacementGuards() {
  const before = await snapshot(), commandCount = requests.length;
  await page.getByRole("button", { name: "Signatures", exact: true }).click(); await padDraw();
  await expect(page.locator(".takeoff-viewport")).toHaveAttribute("data-tool", "signature");
  const fingerprint = () => page.evaluate(() => JSON.parse(window.CeasefireTakeoffs.projectFingerprint()));
  const armed = (await fingerprint()).signatureDraft; assert.ok(armed?.strokes.length);
  const guarded = await page.evaluate(() => { try { window.CeasefireTakeoffs.projectSnapshot(); return false; } catch (error) { return error.message; } });
  assert.match(guarded, /unfinished.*drawing.*before saving/);
  await clickProjectControl(page, "Save");
  // Save validates pricing and all calculator drafts before the drawing guard.
  await expect(page.getByRole("button", { name: "Save", exact: true })).toBeEnabled({ timeout: 30000 });
  await expect(page.locator("#app-message")).toContainText("Project was not saved.");
  assert.equal(projectWrites.length, 0, "An armed signature cannot issue any project save request");
  assert.deepEqual((await fingerprint()).signatureDraft, armed);
  const modal = page.getByRole("dialog", { name: "Discard unfinished edits?", exact: true });
  await page.getByRole("button", { name: "Page ›", exact: true }).click(); await expect(modal).toBeVisible();
  await modal.getByRole("button", { name: "Cancel", exact: true }).click(); await expect(modal).toHaveCount(0);
  await expect(page.getByLabel("Page number", { exact: true })).toHaveValue("1");
  await expect(page.locator(".takeoff-viewport")).toHaveAttribute("data-tool", "signature");
  assert.deepEqual((await fingerprint()).signatureDraft, armed); assert.equal(requests.length, commandCount);
  assert.deepEqual((await fingerprint()).snapshot.items, before.items);
  await renderDrawing(page, async () => { await page.getByRole("button", { name: "Page ›", exact: true }).click(); await expect(modal).toBeVisible();
    await modal.getByRole("button", { name: "Discard edits", exact: true }).click(); }, 2);
  assert.equal((await fingerprint()).signatureDraft, null); await expect(page.locator(".takeoff-viewport")).toHaveAttribute("data-tool", "select");
  assert.equal((await snapshot()).signatures, undefined, "Discarding placement creates no signature record");
  await renderDrawing(page, () => page.getByRole("button", { name: "‹ Page", exact: true }).click(), 1); await fit();
  invariant(await snapshot(), before);
  check("armed signature blocks Save; Cancel navigation retains its draft and explicit discard cancels placement without a record");
}
(async () => {
  const info = await ready; assert.notEqual(info.port, 8765); const originalHash = hash(info.area_fixture);
  browser = await chromium.launch({ headless: true }); page = await browser.newPage({ viewport: { width: 1600, height: 1100 }, deviceScaleFactor: 2 }); page.setDefaultTimeout(30000);
  page.on("pageerror", error => errors.push(error.message)); page.on("request", request => {
    if (request.url().endsWith("/commands")) requests.push(request.postDataJSON());
    if (request.method() === "POST" && /\/api\/project\/save(?:-as)?$/.test(new URL(request.url()).pathname)) projectWrites.push(request.url());
  });
  await page.addInitScript(() => { window.qaCsp = []; document.addEventListener("securitypolicyviolation", event => window.qaCsp.push(event.effectiveDirective)); });
  const response = await page.goto(`http://127.0.0.1:${info.port}/`); assert.ok(!response.headers()["content-security-policy"].includes("unsafe-inline"));
  await page.waitForFunction(() => window.CeasefireDesktop?.status().ready); await page.getByRole("button", { name: "Takeoffs", exact: true }).click();
  await chooseTakeoff(page, "wall"); await renderDrawing(page, () => page.locator("#takeoff-upload").setInputFiles(info.area_fixture), 1); await idle();
  const scale = page.getByLabel("Drawing calibration", { exact: true }); if (!await scale.isVisible()) await page.getByRole("button", { name: "Scale", exact: true }).click();
  await scale.selectOption("scale:100"); await command(() => fillDialog("Apply drawing scale 1:100?", {}, "Apply scale"), "add_calibration");
  await fit(); await page.getByRole("button", { name: "Trace surface", exact: true }).click();
  for (const [index, point] of [[100, 200], [500, 200], [500, 440], [100, 440]].entries())
    if (index === 3) await page.mouse.dblclick(...await screen(point)); else await page.mouse.click(...await screen(point));
  await command(() => fillDialog("Add surface", { "Surface Type": "wall", "Surface ID": "SIGNATURE-BACKGROUND", "Number of layers": 2,
    Level: "L01", Substrate: "Concrete", "Protection system": "Synthetic system", "Protection product": "Synthetic product", "FRL / fire rating": "90/90/90" }, "Add surface"), "create_item");
  await page.getByRole("button", { name: "Select", exact: true }).click();
  await armedPlacementGuards();
  const baseline = await snapshot(), calculators = await page.evaluate(() => window.CeasefireCalculators.completeProjectSnapshot());
  let { record: wall, result } = await insert([200, 360]); invariant(result.snapshot, baseline);
  assert.equal(wall.mode, "wall"); assert.equal(wall.source_sha256, originalHash); assert.equal(wall.version, 1); assert.equal(wall.strokes.length, 2);
  assert.equal((await snapshot()).items.length, 1); await expect(page.locator(".takeoff-area-hit")).toHaveCount(1);
  check("drawn signature overlays an existing Wall markup as independent vector ink without quantity or review changes");

  await panel().getByRole("button", { name: "Close settings", exact: true }).click();
  const beforeStationary = await snapshot(), stationaryCommands = requests.length;
  await signature(wall.id).locator('[data-signature-part="move"]').click(); await expect(panel()).toBeHidden();
  await expect(signature(wall.id)).toHaveAttribute("aria-pressed", "true");
  await signature(wall.id).locator('[data-signature-part="move"]').dblclick();
  await expect(panel().getByRole("heading", { name: "Signature Settings", exact: true })).toBeVisible();
  assert.deepEqual(await snapshot(), beforeStationary); assert.equal(requests.length, stationaryCommands);
  check("stationary single-click selects and native double-click opens Signature Settings without creating edits");

  result = await command(() => drag(signature(wall.id).locator('[data-signature-part="move"]'), 28, 18), "update_signature");
  let moved = result.snapshot.signatures.records.find(value => value.id === wall.id), delta = moved.quad_pdf[0].map((n, axis) => n - wall.quad_pdf[0][axis]);
  assert.ok(delta.some(n => Math.abs(n) > 1)); for (const [index, point] of wall.quad_pdf.entries()) for (let axis = 0; axis < 2; axis++) assert.ok(Math.abs(moved.quad_pdf[index][axis] - point[axis] - delta[axis]) < 1e-8);
  assert.deepEqual(moved.strokes, wall.strokes); invariant(result.snapshot, baseline); await select(wall.id);
  result = await command(() => drag(signature(wall.id).locator(".takeoff-signature-resize"), 24, 16), "update_signature");
  let current = result.snapshot.signatures.records.find(value => value.id === wall.id);
  assert.deepEqual(current.quad_pdf[0], moved.quad_pdf[0]); assert.deepEqual(current.strokes, moved.strokes);
  const dimensions = record => [Math.hypot(...record.quad_pdf[1].map((n, axis) => n - record.quad_pdf[0][axis])), Math.hypot(...record.quad_pdf[3].map((n, axis) => n - record.quad_pdf[0][axis]))];
  assert.ok(dimensions(current).every((n, axis) => n > dimensions(moved)[axis])); invariant(result.snapshot, baseline);
  check("native dragging and corner resizing update only the signature placement with its stable identity and strokes");

  const beforeVisibility = await snapshot(), visibilityCommands = requests.length;
  let eye = panel().getByRole("button", { name: "Visibility", exact: true }); const mainEye = page.locator(".takeoff-tool-rail").getByRole("button", { name: "Visibility", exact: true });
  await eye.click(); await expect(signature(wall.id)).toHaveCount(0); await expect(page.locator(".takeoff-area-hit")).toHaveCount(1);
  await mainEye.click(); await expect(page.locator(".takeoff-signature,.takeoff-area-hit")).toHaveCount(0); await mainEye.dblclick();
  await expect(signature(wall.id)).toBeVisible(); await expect(mainEye).toHaveAttribute("aria-pressed", "false");
  eye = panel().getByRole("button", { name: "Visibility", exact: true }); await expect(eye).toHaveAttribute("aria-pressed", "false");
  assert.deepEqual(await snapshot(), beforeVisibility); assert.equal(requests.length, visibilityCommands);
  check("local hide and main-eye double-click restore signature ink without canonical edits");

  const beforeRedraw = current; result = await command(async () => { await panel().getByRole("button", { name: "Redraw signature", exact: true }).click(); await padDraw(true); }, "update_signature");
  current = result.snapshot.signatures.records.find(value => value.id === wall.id); assert.notDeepEqual(current.strokes, beforeRedraw.strokes);
  assert.deepEqual(current.quad_pdf, beforeRedraw.quad_pdf); assert.equal(current.id, beforeRedraw.id); invariant(result.snapshot, baseline);
  const chosen = await page.evaluate(() => JSON.parse(localStorage.getItem("ceasefire.takeoff-signature.v1")));
  const retainedRatio = dimensions(beforeRedraw)[0] / dimensions(beforeRedraw)[1], sx = Math.min(1, chosen.ratio / retainedRatio), sy = Math.min(1, retainedRatio / chosen.ratio);
  assert.deepEqual(current.strokes, chosen.strokes.map(stroke => stroke.map(([x, y]) => [x * sx + (1 - sx) / 2, y * sy + (1 - sy) / 2])), "Redraw centers padding instead of stretching replacement ink");
  const points = current.strokes.flat(), xs = points.map(point => point[0]), ys = points.map(point => point[1]);
  const inkRatio = (Math.max(...xs) - Math.min(...xs)) * retainedRatio / (Math.max(...ys) - Math.min(...ys));
  assert.ok(Math.abs(inkRatio - chosen.ratio) < 1e-8, "Rendered replacement ink preserves the drawn signature's physical proportions");
  await signature(wall.id).focus(); result = await command(() => signature(wall.id).press("Delete"), "delete_signature");
  assert.equal(result.snapshot.signatures.records.length, 0); await expect(signature(wall.id)).toHaveCount(0);
  result = await command(() => page.getByRole("button", { name: "Undo last edit", exact: true }).click(), "undo");
  wall = result.snapshot.signatures.records.find(value => value.id === current.id);
  for (const key of Object.keys(current).filter(key => key !== "version")) assert.deepEqual(wall[key], current[key]);
  await expect(signature(wall.id)).toBeVisible(); invariant(result.snapshot, baseline);
  check("redraw preserves placement; keyboard Delete and Undo restore exact signature identity, ink and metadata");

  // The visible surface navigation is combined. Use the retained compatibility
  // mode only to establish an existing native Floor scope without rewriting it.
  assert.equal(await page.evaluate(() => window.CeasefireTakeoffs.selectWorkspace("slab")), true); await fit();
  const { record: floor } = await insert([530, 350], true); assert.equal(floor.mode, "slab"); invariant(await snapshot(), baseline);
  await chooseTakeoff(page, "wall"); await fit(); await expect(page.locator(".takeoff-signature")).toHaveCount(2);
  const combined = await download("wall-floor-signatures.pdf", [wall.id, floor.id]); assert.equal(combined.matches.length, 2);
  check("Walls/Floors shows and exports both native Wall and Floor signatures as actual PDF vector strokes");

  const physical = {};
  for (const [scope, name, point] of [["defect_reports", "Defect Reports", [230, 330]], ["service_plans", "Service Plans", [490, 320]]]) {
    await chooseTakeoff(page, name); await fit(); const scopeBaseline = await snapshot();
    const { record, result: created } = await insert(point, true); physical[scope] = record; assert.equal(record.mode, scope);
    invariant(created.snapshot, scopeBaseline); await expect(page.locator(".takeoff-signature")).toHaveCount(1);
    const pdf = await download(`${scope}-signature.pdf`, [record.id], scope); assert.equal(pdf.matches.length, 1);
  }
  await chooseTakeoff(page, "Defect Reports"); await expect(signature(physical.defect_reports.id)).toBeVisible(); await expect(signature(physical.service_plans.id)).toHaveCount(0);
  await chooseTakeoff(page, "Service Plans"); await expect(signature(physical.service_plans.id)).toBeVisible(); await expect(signature(physical.defect_reports.id)).toHaveCount(0);
  check("Defect Reports and Service Plans preserve separate signature scopes in both rendered drawing and real marked PDF requests");

  const reopened = await saveLoad(info); assert.equal(reopened.signatures.records.length, 4); assert.equal(reopened.items.length, 1);
  assert.deepEqual(await page.evaluate(() => window.CeasefireCalculators.completeProjectSnapshot()), calculators); assert.equal(hash(info.area_fixture), originalHash);
  await expect(page.locator(".takeoff-signature")).toHaveCount(2); assert.deepEqual(errors, []); assert.deepEqual(await page.evaluate(() => window.qaCsp), []);
  check("Save/Load restores four signatures exactly; original source and calculator inputs remain unchanged with zero page/CSP errors");
  await page.screenshot({ path: path.join(output, "wall-floor-signatures.png"), fullPage: true });
  fs.writeFileSync(path.join(output, "result.json"), JSON.stringify({ completed: true, check_count: checks.length, checks, signature_count: 4, item_count: 1,
    fixture_port: info.port, original_source_sha256: originalHash, source_before_sha256: sourceBefore, source_after_sha256: hashes(), errors, csp: await page.evaluate(() => window.qaCsp), requests, projectWrites, pdfExports }, null, 2));
  console.log(`PASS: ${checks.length} signature acceptance checks, four independent signatures and three real PDF exports. Evidence: ${output}`);
})().catch(async error => { console.error(error); process.exitCode = 1; if (page) { await page.screenshot({ path: path.join(output, "failure.png"), fullPage: true }).catch(() => {});
  fs.writeFileSync(path.join(output, "failure.txt"), await page.locator("body").innerText().catch(() => "")); }
  fs.writeFileSync(path.join(output, "failure.json"), JSON.stringify({ completed: false, checks, errors, requests, projectWrites, pdfExports, error: String(error), source_before_sha256: sourceBefore, source_after_sha256: hashes() }, null, 2));
}).finally(async () => { fs.writeFileSync(path.join(output, "server.log"), logs); await browser?.close(); server.kill(); });
