"""Native Microsoft Excel regressions for all three imported calculators.

Expected values are immutable captures from disposable original-workbook copies,
never generated by WorkbookEngine. Raw inputs, bulk ranges, formula exceptions,
Excel build and source hashes remain in each fixture for reproducibility.
"""

from copy import deepcopy
import gzip
import hashlib
import json
import math
from pathlib import Path
import re
import unittest

from estimator.excel_engine import WorkbookEngine
from estimator.workbook_calculators import approved_formula_overrides, source_model
from estimator.workbook_catalog import column_name, column_number


FIXTURES = Path(__file__).resolve().parent / "fixtures" / "calculators"
IDENTIFIERS = ("ductwork", "steel_board", "steel_vermiculite")
SOURCE_FORMULA_COUNTS = {"ductwork": 24059, "steel_board": 16534, "steel_vermiculite": 120973}
VARIATION_COUNTS = {"ductwork": (3, 21777), "steel_board": (10, 99854), "steel_vermiculite": (8, 136408)}


def read_fixture(identifier, kind):
    with gzip.open(FIXTURES / f"{identifier}-{kind}.json.gz", "rt", encoding="utf-8-sig") as source:
        return json.load(source)


def scenario_inputs(scenario):
    """Apply ordinary inputs, then bulk writes in the native capture order."""
    inputs = deepcopy(scenario.get("inputs") or {})
    for block in scenario.get("input_blocks") or []:
        match = re.fullmatch(r"([A-Z]+)([1-9]\d*):([A-Z]+)([1-9]\d*)", block["range"])
        if not match:
            raise ValueError("Oracle input block must be a bounded A1 rectangle")
        first_column, first_row = column_number(match[1]), int(match[2])
        last_column, last_row = column_number(match[3]), int(match[4])
        values = block["values"]
        if len(values) != last_row - first_row + 1 or any(len(row) != last_column - first_column + 1 for row in values):
            raise ValueError("Oracle input block dimensions do not match its values")
        sheet = inputs.setdefault(block["sheet"], {})
        for row_offset, row in enumerate(values):
            for column_offset, value in enumerate(row):
                sheet[f"{column_name(first_column+column_offset)}{first_row+row_offset}"] = value
    # The capture writes formula exceptions last. No fixture should disguise an
    # overlapping scalar override, because engine overlays intentionally win.
    for sheet, formulas in (scenario.get("formula_overrides") or {}).items():
        if set(formulas) & set(inputs.get(sheet, {})):
            raise ValueError("Oracle scalar inputs overlap a formula exception")
    return inputs


def excel_equal(actual, expected):
    numeric = type(actual) in (int, float) and type(expected) in (int, float)
    if numeric:
        return math.isclose(actual, expected, abs_tol=1e-10, rel_tol=1e-12)
    return type(actual) is type(expected) and actual == expected


class NativeFixtureIntegrityTests(unittest.TestCase):
    def test_capture_bytes_source_hashes_excel_provenance_and_complete_counts(self):
        manifest = json.loads((FIXTURES / "manifest.json").read_text(encoding="utf-8"))
        counts = {"default": 0, "variations": 0}
        for entry in manifest["fixtures"]:
            with self.subTest(fixture=entry["filename"]):
                payload = (FIXTURES / entry["filename"]).read_bytes()
                self.assertEqual(hashlib.sha256(payload).hexdigest(), entry["gzip_sha256"])
                original = gzip.decompress(payload)
                self.assertEqual(hashlib.sha256(original).hexdigest(), entry["capture_sha256"])
                fixture = json.loads(original.decode("utf-8-sig"))
                identifier, kind = entry["id"], entry["kind"]
                self.assertEqual(fixture["id"], identifier)
                self.assertEqual(fixture["source_sha256"], source_model(identifier)["source"]["sha256"])
                self.assertEqual(fixture["oracle"]["application"], "Microsoft Excel")
                self.assertTrue(fixture["oracle"]["version"])
                self.assertTrue(fixture["oracle"]["build"])
                self.assertTrue(fixture["oracle"]["captured_utc"])
                count = sum(len(cells) for scenario in fixture["scenarios"] for cells in scenario["expected"].values())
                counts[kind] += count
                if kind == "default":
                    default = next(scenario for scenario in fixture["scenarios"] if scenario["id"] == "source_default_full")
                    self.assertEqual(sum(len(cells) for cells in default["expected"].values()), SOURCE_FORMULA_COUNTS[identifier])
                    self.assertFalse(default["inputs"])
                    self.assertFalse(default["formula_overrides"])
                else:
                    self.assertEqual((len(fixture["scenarios"]), count), VARIATION_COUNTS[identifier])
                    self.assertTrue(all(scenario.get("input_blocks") for scenario in fixture["scenarios"]))
                    self.assertTrue(all(scenario.get("coverage") for scenario in fixture["scenarios"]))
                for scenario in fixture["scenarios"]:
                    if scenario.get("formula_overrides"):
                        runtime_overrides = approved_formula_overrides(identifier)
                        # Immutable captures cover the original source capacity;
                        # runtime applies the same approved translation to new rows.
                        self.assertEqual(scenario["formula_overrides"], {
                            sheet: {address: runtime_overrides[sheet][address] for address in formulas}
                            for sheet, formulas in scenario["formula_overrides"].items()})
        self.assertEqual(counts, {"default": 161566 + 300, "variations": 258039})
        self.assertEqual(len(manifest["fixtures"]), 6)

    def test_overlay_order_preserves_zero_blank_empty_text_decimal_and_boolean(self):
        scenario = {"inputs": {"Sheet": {"A1": 999, "Z1": 3.141592653589793}},
                    "input_blocks": [{"sheet": "Sheet", "range": "A1:C2", "values": [[None, "", 0], [1.23456789, False, True]]}]}
        self.assertEqual(scenario_inputs(scenario), {"Sheet": {"A1": None, "B1": "", "C1": 0,
                         "A2": 1.23456789, "B2": False, "C2": True, "Z1": 3.141592653589793}})
        self.assertEqual(scenario["inputs"]["Sheet"]["A1"], 999)
        self.assertFalse(excel_equal(False, 0))
        self.assertFalse(excel_equal("", None))
        self.assertTrue(excel_equal(1, 1.0))
        self.assertTrue(excel_equal("#VALUE!", "#VALUE!"))


class NativeExcelParityTests(unittest.TestCase):
    def compare_capture(self, identifier, kind):
        model = source_model(identifier)
        fixture = read_fixture(identifier, kind)
        self.assertEqual(fixture["source_sha256"], model["source"]["sha256"])
        for scenario in fixture["scenarios"]:
            with self.subTest(calculator=identifier, fixture=kind, scenario=scenario["id"]):
                engine = WorkbookEngine(model, scenario_inputs(scenario), scenario.get("formula_overrides"))
                mismatches = []
                for sheet, cells in scenario["expected"].items():
                    for address, expected in cells.items():
                        try:
                            actual = engine.value(sheet, address)
                            if not excel_equal(actual, expected):
                                mismatches.append((sheet, address, expected, actual))
                        except Exception as error:
                            mismatches.append((sheet, address, expected, repr(error)))
                self.assertFalse(mismatches, f"{len(mismatches)} Excel discrepancies; first20: {mismatches[:20]!r}")

    def test_ductwork_all_default_formulas_and_approved_instruction_exception(self):
        self.compare_capture("ductwork", "default")

    def test_steel_board_all_default_formulas(self):
        self.compare_capture("steel_board", "default")

    def test_steel_vermiculite_all_default_formulas(self):
        self.compare_capture("steel_vermiculite", "default")

    def test_ductwork_all_native_variations(self):
        self.compare_capture("ductwork", "variations")

    def test_steel_board_all_native_variations(self):
        self.compare_capture("steel_board", "variations")

    def test_steel_vermiculite_all_native_variations(self):
        self.compare_capture("steel_vermiculite", "variations")


if __name__ == "__main__":
    unittest.main()
