"use strict";
const assert = require('node:assert/strict');
const S = require('../static/takeoff-search.js');
const run = (str, x, y = 100, extra = {}) => ({ str, width: str.length * 5, height: 10, transform: [10, 0, 0, 10, x, y], ...extra });
const source = [run('A fire ', 20), run('rated', 55), run(' wall protects cable. Wall remains.', 80)];
const saved = JSON.stringify(source), index = S.indexText(source);
assert.equal(index.text, 'a fire rated wall protects cable. wall remains.');
const phrase = S.find(index, ' FIRE\nRATED   WALL ');
assert.equal(phrase.length, 1); assert.equal(phrase[0].matching.length, 3);
assert.equal(phrase[0].text, 'A fire rated wall protects cable.');
assert.deepEqual(phrase[0].matching.map(span => source[span.item].str.slice(span.start, span.end)), ['fire ', 'rated', ' wall']);
const repeated = S.find(index, 'wall'); assert.equal(repeated.length, 2);
assert.notEqual(repeated[0].start, repeated[1].start); assert.equal(repeated[1].text.trim(), 'Wall remains.');
assert.equal(JSON.stringify(source), saved, 'Indexing/highlights preserve PDF source text and transforms');
const contiguous = S.indexText([run('Fire', 0), run('stop', 20), run(' door.', 40)]);
assert.equal(contiguous.text, 'firestop door.'); assert.equal(S.find(contiguous, 'firestop')[0].text, 'Firestop door.');
const newline = S.indexText([run('Fire', 0, 120, { hasEOL: true }), run('rated wall.', 0, 100)]);
assert.equal(S.find(newline, 'fire rated').length, 1, 'Phrase spans true PDF lines');
const unicode = S.find(S.indexText([run('İ WALL', 0)]), 'wall')[0]; assert.equal(unicode.matching[0].start, 2, 'Case expansion retains exact original offsets');
const hits = [{ id: 'top', points: [[0, 90]] }, { id: 'centre', points: [[0, 50]] }, { id: 'bottom', points: [[0, 10]] }];
assert.equal(S.choose(hits, null, [0, 45]).id, 'centre');
assert.equal(S.choose(hits, 'centre', [0, 45]).id, 'bottom');
assert.equal(S.choose(hits, 'bottom', [0, 45]).id, 'top');
assert.equal(S.choose([{ id: 'a', points: [[0, 1]] }, { id: 'b', points: [[0, -1]] }], null, [0, 0]).id, 'a', 'Nearest ties retain stable reading order');
assert.equal(S.choose([], null, [0, 0]), null);
assert.equal(S.find(S.indexText([run('wall '.repeat(510), 0)]), 'wall').length, 500);
assert.throws(() => S.indexText([run('x'.repeat(S.MAX_PAGE_TEXT + 1), 0)]), /bounded search limit/);
assert.throws(() => S.find(index, 'x'.repeat(201)), /200 characters/);
assert.equal(S.runQuad({ transform: [0, 10, -10, 0, 100, 200], width: 20, height: 10 }).length, 4);
assert.equal(S.runQuad({ transform: [NaN, 0, 0, 10, 20, 20], width: 20 }), null, 'Invalid geometry never becomes invented word bounds');
console.log('PASS search source spans, cross-run/line phrases, repeated hits, Unicode offsets, nearest/wrap, limits and original coordinates.');
