import json
import math
from pathlib import Path
import unittest

from estimator.calculator import calculate, fields, masking_breakdown, specification
from estimator.catalog import baseline, ValidationError


class CalculatorTests(unittest.TestCase):
    def test_all_saved_excel_formula_caches(self):
        result = calculate()
        self.assertEqual(result["errors"], {})
        self.assertEqual(len(specification()["cached"]), 151)
        self.assertEqual(len(fields()), 64)
        for cell, expected in specification()["cached"].items():
            with self.subTest(cell=cell):
                actual = result["cells"][cell]
                if isinstance(expected, (int, float)):
                    self.assertTrue(math.isclose(actual, expected, rel_tol=1e-12, abs_tol=1e-9), (actual, expected))
                else:
                    self.assertEqual(actual, expected)

    def test_zero_area_does_not_hide_other_totals(self):
        result = calculate({"B8": 0})
        self.assertEqual(result["cells"]["F8"], "#DIV/0!")
        self.assertEqual(result["summary"]["total"], 1260)
        self.assertIsNone(result["summary"]["rate"])

    def test_blank_quantity_and_invalid_selection_are_distinct(self):
        self.assertEqual(calculate({"B15": None})["summary"]["total"], 1260)
        result = calculate({"D15": ""})
        self.assertEqual(result["cells"]["A63"], "#N/A")
        self.assertIsNone(result["summary"]["total"])
        self.assertEqual(calculate({"D15": "Missing workbook product"})["cells"]["A63"], "#N/A")

    def test_calculated_cells_and_nonfinite_values_cannot_be_overwritten(self):
        for inputs in ({"F7": 1}, {"B15": float("nan")}, {"B15": True}, {"D15": 123}, {"B15": "1.2"}, [], False):
            with self.subTest(inputs=inputs), self.assertRaises(ValidationError):
                calculate(inputs)

    def test_no_rounding_of_material_quantity_or_money_before_totals(self):
        result = calculate({"B15": 0.5, "B9": 0, "D2": "N/A", "F27": 0, "F28": 0})
        self.assertEqual(result["cells"]["D35"], 0.6)
        self.assertTrue(math.isclose(result["summary"]["total"], 43.1262, abs_tol=1e-12))
        self.assertIn("1 x Promat Cafco 300", result["notes"])

    def test_notes_that_resemble_excel_errors_are_literal_text(self):
        for notes in ("#N/A", "#VALUE! - awaiting site details", "#DIV/0! is a formula error"):
            result = calculate({"B12": notes})
            self.assertEqual(result["errors"], {})
            self.assertTrue(result["notes"].startswith(notes + "\n\n---Materials---"))

    def test_masking_breakdown_preserves_excel_errors_and_old_snapshots(self):
        result = calculate({"B15": 1, "C15": 1e-307})
        self.assertEqual(result["masking"]["labour_total"], "#NUM!")
        self.assertEqual(result["masking"]["material_base_total"], "#NUM!")
        json.dumps(result, allow_nan=False)
        original = calculate({"B15": 35.75, "B26": 0.12, "B27": 0.25})
        expected = original.pop("masking")
        self.assertEqual(masking_breakdown(original), expected)


class ExcelOracleTests(unittest.TestCase):
    def test_independently_recalculated_excel_scenarios(self):
        path = Path(__file__).parent / "fixtures" / "excel-calculator-oracle.json"
        # The checked-in fixture is required in CI and never generated by this engine.
        self.assertTrue(path.is_file(), "Missing independently recalculated Excel fixtures")
        oracle = json.loads(path.read_text(encoding="utf-8-sig"))
        data = baseline()
        source_index = {}
        for rows in data["rate_groups"].values():
            for rate in rows:
                for field in ("price", "yield"):
                    source = rate["source"].get(field)
                    if source:
                        source_index[source.replace("Lists!", "")] = (rate["id"], field)
        for scenario in oracle["scenarios"]:
            with self.subTest(scenario=scenario["id"]):
                configuration = {"rates": {}}
                for source, expected in scenario.get("lookupOverrides", {}).items():
                    rate_id, field = source_index[source.replace("Lists!", "")]
                    configuration["rates"].setdefault(rate_id, {})[field] = expected
                actual = calculate(scenario["inputs"], configuration)
                # Reconcile the report's non-overlapping cost components to Excel,
                # using the independently captured workbook totals as the oracle.
                expected_cells = scenario["expected"]
                if isinstance(expected_cells["F7"], (int, float)):
                    c, masking = actual["cells"], actual["masking"]
                    labour = sum(c[f"F{row}"] for row in (65, 70, 79, 84, 89, 94, 99, 104)) + masking["labour_total"] + sum(c[f"D{row}"] for row in (112, 113, 119))
                    materials = sum(c[f"F{row}"] for row in (63, 68, 73, 77, 82, 87, 92, 97, 102)) + masking["material_base_total"] + masking["material_adjustment"] + c["D114"]
                    access = c["D115"] + c["D116"]
                    travel = c["D117"] + c["D118"]
                    for cell, amount in (("F2", labour), ("F3", materials), ("F4", access), ("F5", travel), ("F7", labour + materials + access + travel + c["D27"])):
                        self.assertTrue(math.isclose(amount, expected_cells[cell], rel_tol=1e-12, abs_tol=1e-8), (scenario["id"], cell, amount, expected_cells[cell]))
                for cell, expected in scenario["expected"].items():
                    with self.subTest(cell=cell):
                        result = actual["cells"].get(cell)
                        if isinstance(expected, (int, float)):
                            self.assertIsInstance(result, (int, float), f"{cell}: {result}, expected {expected}")
                            self.assertTrue(math.isclose(result, expected, rel_tol=1e-12, abs_tol=1e-8), f"{cell}: {result} != {expected}")
                        else:
                            self.assertEqual(result, expected, cell)


if __name__ == "__main__":
    unittest.main()
